### ISSUE TITLE
A SegV is reported when using edit-config to operate the Datastore, but using the sysrepocfg is OK

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1356]
Hi 
I have another issue when using edit-config to operate the Datastore:
Whether the yang validation is the same between using sysrepocfg --merge or edit-config in netopee2-cli

Now, for one same XML file, when using the sysrepocfg --merge, it could report the right error:
```
# sysrepocfg --merge=success-ok/ansi41-map-parameters-system-id.xml --format=xml nokia-tas-structure --datastore=running
[ERR] Input data are not valid: system-id must be entered when ANSI41 is enabled! (/nokia-tas-structure:scc-as-parameters/ansi41-map-parameters:ss7-map-parameters)
Errors were encountered during importing. Cancelling the operation.
```

But when I use the edit-config in netopeer2-cli, one SegV is reported.
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff59a8700 (LWP 1170)]
0x00007ffff6d15223 in resolve_unres_data (ctx=0x7fffe4a58e90, unres=0x7fff39bdc1b0, root=0x7fff39bbf6c0, 
    options=16897) at /root/test/source/libyang/src/resolve.c:8329
8329                            for (parent = unres->node[j]; parent; parent = parent->parent) {
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libev-4.15-7.el7.x86_64 pcre-8.32-17.el7.x86_64 protobuf-c-1.0.2-3.el7.x86_64
(gdb) 
(gdb) bt
#0  0x00007ffff6d15223 in resolve_unres_data (ctx=0x7fffe4a58e90, unres=0x7fff39bdc1b0, root=0x7fff39bbf6c0, 
    options=16897) at /root/test/source/libyang/src/resolve.c:8329
#1  0x00007ffff6d9f810 in lyd_defaults_add_unres (root=0x7fff39bbf6c0, options=16897, ctx=0x7fffe4a58e90, 
    data_tree=0x7fff39b7ef00, act_notif=0x0, unres=0x7fff39bdc1b0, wd=1)
    at /root/test/source/libyang/src/tree_data.c:7273
#2  0x00007ffff6d9a66c in lyd_validate (node=0x7fff39bbf6c0, options=16897, var_arg=0x7fffe4a58e90)
    at /root/test/source/libyang/src/tree_data.c:5098
#3  0x00007ffff7b12ec2 in dm_validate_data_info () from /lib64/libsysrepo.so.0.7
#4  0x00007ffff7b193aa in dm_validate_session_data_trees () from /lib64/libsysrepo.so.0.7
#5  0x00007ffff7afb28c in rp_dt_commit () from /lib64/libsysrepo.so.0.7
#6  0x00007ffff7acbb12 in rp_commit_req_process () from /lib64/libsysrepo.so.0.7
#7  0x00007ffff7ade291 in rp_req_dispatch () from /lib64/libsysrepo.so.0.7
#8  0x00007ffff7ae1783 in rp_worker_thread_execute () from /lib64/libsysrepo.so.0.7
#9  0x00007ffff7645dd5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff6a1bb3d in clone () from /lib64/libc.so.6
(gdb) 
```
As the yang file is huge, I'm trying to reproduce with a simple yang file.

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi,
It's strange, when I use ```edit-config``` to operate the ```candidate``` DataStore, it's OK.
And when the Datastore is ```running```, the SegV is reported.
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff49a6700 (LWP 5020)]
0x00007ffff6d0f868 in resolve_must (node=0x7fff35275a80, inout_parent=0, ignore_fail=0)
    at /root/test/source/libyang/src/resolve.c:6129
6129        struct ly_ctx *ctx = node->schema->module->ctx;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libev-4.15-7.el7.x86_64 pcre-8.32-17.el7.x86_64 protobuf-c-1.0.2-3.el7.x86_64
(gdb) bt
#0  0x00007ffff6d0f868 in resolve_must (node=0x7fff35275a80, inout_parent=0, ignore_fail=0)
    at /root/test/source/libyang/src/resolve.c:6129
#1  0x00007ffff6d14ab1 in resolve_unres_data_item (node=0x7fff35275a80, type=UNRES_MUST, ignore_fail=0, 
    failed_when=0x0) at /root/test/source/libyang/src/resolve.c:8139
#2  0x00007ffff6d155e7 in resolve_unres_data (ctx=0x7fffe462c770, unres=0x7fff35277b90, root=0x7fff35254510, 
    options=16897) at /root/test/source/libyang/src/resolve.c:8435
#3  0x00007ffff6d9f810 in lyd_defaults_add_unres (root=0x7fff35254510, options=16897, ctx=0x7fffe462c770, 
    data_tree=0x7fff35274820, act_notif=0x0, unres=0x7fff35277b90, wd=1)
    at /root/test/source/libyang/src/tree_data.c:7273
#4  0x00007ffff6d9a66c in lyd_validate (node=0x7fff35254510, options=16897, var_arg=0x7fffe462c770)
    at /root/test/source/libyang/src/tree_data.c:5098
#5  0x00007ffff7b12ec2 in dm_validate_data_info () from /lib64/libsysrepo.so.0.7
#6  0x00007ffff7b193aa in dm_validate_session_data_trees () from /lib64/libsysrepo.so.0.7
#7  0x00007ffff7afb28c in rp_dt_commit () from /lib64/libsysrepo.so.0.7
#8  0x00007ffff7acbb12 in rp_commit_req_process () from /lib64/libsysrepo.so.0.7
#9  0x00007ffff7ade291 in rp_req_dispatch () from /lib64/libsysrepo.so.0.7
#10 0x00007ffff7ae1783 in rp_worker_thread_execute () from /lib64/libsysrepo.so.0.7
#11 0x00007ffff7645dd5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff6a1bb3d in clone () from /lib64/libc.so.6
```
I will use the valgrind to startup the sysrepo-netopeer2 server, then edit-config to reproduce it again.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
firstly, use the most recent *libyang*. Then, if you want to debug this yourself, go ahead. If you want me to look at it then instead of posting these outputs, provide all the required files and steps how to reproduce the issue, thanks.

Regards,
Michal

**Comment by darcyllingyan** [comment]
After use the latest packages and re-install, the SegV isn't reproduced now. Will close the issue.
