### ISSUE TITLE
[New-Sysrepo] [API sr_module_change_subscribe] SEGFAULT 

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1569]
Hi

After adding a work around for #1568 observed below crash. And I couldnt find the root cause for this. Please help.

```
(gdb) bt
#0  _int_malloc (av=av@entry=0x7f5c618f6c40 <main_arena>, bytes=bytes@entry=45) at malloc.c:3779
#1  0x00007f5c615a20fc in __GI___libc_malloc (bytes=bytes@entry=45) at malloc.c:3057
#2  0x00007f5c61593620 in _IO_vasprintf (result_ptr=0x7ffe5f255800, format=<optimized out>, args=args@entry=0x7ffe5f2556c0) at vasprintf.c:73
#3  0x00007f5c61570154 in ___asprintf (string_ptr=<optimized out>, format=<optimized out>) at asprintf.c:35
#4  0x00007f5c61911912 in sr_path_evpipe (evpipe_num=1, path=0x7ffe5f255800) at /opt/dev/sysrepo/src/common.c:1367
#5  0x00007f5c61908952 in sr_subs_new (conn=0x55dfdbfbf340, opts=16, subs_p=0x7ffe5f255910) at /opt/dev/sysrepo/src/sysrepo.c:3001
#6  0x00007f5c61908dbb in sr_module_change_subscribe (session=0x55dfdc1ff970, module_name=0x55dfdae7c3fc "module-name", xpath=0x0, callback=0x55dfdae5ad7c <service_change_cb>, private_data=0x55dfdc1d4740, priority=0, opts=16, subscription=0x7ffe5f255910)
    at /opt/dev/sysrepo/src/sysrepo.c:3101
#7  0x000055dfdae13211 in main ()
```

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Issue not reproducible.
