### ISSUE TITLE
[New sysrepo] sysrepoctl crash at lyd_mods.c:1351

### ISSUE THREAD

**Issue by brchiu** [sysrepo/sysrepo#1617]
Steps to reproduce
1. `make sr_clean` and `make uninstall_with_repo`
2. reinstall new sysrepo `sudo make install`
3. install new netopeer2-server with `sudo make install`
4. execute new netopeer2-server with `sudo netopeer2-server -d -v 4`
5. execute new netopeer2-cli and connect to new netopeer2-server
6. run get-schema --model ietf-netconf-server
7. disconnect from new netpeer2-cli and quit
8. execute `sudo sysrepoctl -l' then crash

```
brchiu@EROICA:~$ sudo gdb sysrepoctl
GNU gdb (Ubuntu 8.1-0ubuntu3.1) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sysrepoctl...done.
(gdb) br sysrepo.c:149
No source file named sysrepo.c.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (sysrepo.c:149) pending.
(gdb) r -l
Starting program: /usr/local/bin/sysrepoctl -l
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, sr_connect (opts=0, conn_p=0x7fffffffe198) at /home/brchiu/Projects/sysrepo/src/sysrepo.c:149
149	    if ((err_info = sr_lydmods_exists(&exists))) {
(gdb) n
152	    if (!exists) {
(gdb) p exists
$1 = 1
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ba6c55 in sr_lydmods_ctx_load_modules (sr_mods=0x0, ly_ctx=0x55555575a580, removed=1, updated=1, change=0x0)
    at /home/brchiu/Projects/sysrepo/src/lyd_mods.c:1351
1351	    LY_TREE_FOR(sr_mods->child, sr_mod) {
(gdb) p sr_mods
$2 = (const struct lyd_node *) 0x0
(gdb) bt
#0  0x00007ffff7ba6c55 in sr_lydmods_ctx_load_modules (sr_mods=0x0, ly_ctx=0x55555575a580, removed=1, updated=1, change=0x0)
    at /home/brchiu/Projects/sysrepo/src/lyd_mods.c:1351
#1  0x00007ffff7b817b9 in sr_connect (opts=0, conn_p=0x7fffffffe198) at /home/brchiu/Projects/sysrepo/src/sysrepo.c:181
#2  0x0000555555556e86 in main (argc=2, argv=0x7fffffffe4f8) at /home/brchiu/Projects/sysrepo/src/executables/sysrepoctl.c:551
```

**Comment by michalvasko** [comment]
Hi,
right, should not crash anymore.

Regards,
Michal
