### ISSUE TITLE
sysrepoctl SIGSEGV @ lyd_mods.c:849

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1728]
Using "devel" branches for libyang and sysrepo (cloned on Dec 25).

# sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.27 (SO v4.1.14)

# yanglint --version
yanglint SO 1.5.5

Steps to reproduce:
==============

1. Initial state:
```
    # sysrepoctl -l
    Sysrepo repository: /etc/sysrepo

    Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
    -------------------------------------------------------------------------------------------------
    ietf-netconf               | 2011-06-01 | I     | root:root | 666         |            |         
    ietf-netconf-notifications | 2012-02-06 | I     | root:root | 666         |            |         
    ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 666         |            |         
    ietf-origin                | 2018-02-14 | I     | root:root | 666         |            |         
    ietf-yang-library          | 2019-01-04 | I     | root:root | 666         |            |         
    yang                       | 2017-02-20 | I     | root:root | 666         |            |
```
2. There are no other sysrepo clients:
    # sysrepoctl -C
    0

3. Add with "sysrepoctl -i ... -s ..." following YANG models:
    ietf/ietf-interfaces.yang
    ietf/iana-if-type.yang
    openconfig/interfaces/openconfig-interfaces.yang
    openconfig/ospf/openconfig-ospfv2.yang
    openconfig/network-instance/openconfig-network-instance-types.yang
    openconfig/interfaces/openconfig-if-ethernet.yang
    openconfig/interfaces/openconfig-if-ethernet-ext.yang
    openconfig/interfaces/openconfig-if-aggregate.yang
    openconfig/vlan/openconfig-vlan.yang
    openconfig/interfaces/openconfig-if-ip.yang
    openconfig/policy/openconfig-routing-policy.yang
    openconfig/bgp/openconfig-bgp-policy.yang
    openconfig/network-instance/openconfig-network-instance.yang

    No error messages from sysrepoctl so far.

4. Run sysrepoctl -l:
```
    # sysrepoctl -v debug -l
    [INF]: Applying scheduled changes.
    [INF]: File "openconfig-network-instance@2019-05-14.yang" was installed.
    [INF]: Module "openconfig-network-instance" was installed.
    Segmentation fault (core dumped)
```
5. Back trace from core dump:
```
    Program terminated with signal SIGSEGV, Segmentation fault.
    (gdb) bt
    #0  0xb7f3526d in sr_lydmods_add_all_deps (ly_mod=<optimized out>, ly_mod=<optimized out>, sr_mod=0x806efe0)
    at /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/lyd_mods.c:849
    #1  sr_lydmods_sched_apply (sr_mods=0x8072740, new_ctx=0x804e2e0, change=0xbfd1fda4, fail=0xbfd1fdac)
    at /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/lyd_mods.c:2026
    #2  0xb7f1970a in sr_conn_lydmods_ctx_update (changed=0xbfd1fda4, sr_mods=0xbfd1fd9c, apply_sched=1, conn=0x804e1f0)
    at /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/sysrepo.c:157
    #3  sr_connect (opts=0, conn_p=0xbfd1fe30) at /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/sysrepo.c:245
    #4  0x08049440 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/executables/sysrepoctl.c:573
(gdb)

    (gdb) f 0
    #0  0xb7f3526d in sr_lydmods_add_all_deps (ly_mod=<optimized out>, ly_mod=<optimized out>, sr_mod=0x806efe0)
    at /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/lyd_mods.c:849
    849     in /usr/src/debug/sysrepo/1.3.21+gitAUTOINC+353faffe13-r0/git/src/lyd_mods.c
    (gdb) p set2->set.d
    $1 = (struct lyd_node **) 0x0
    (gdb) 
```
So SIGSEGV happens in 
```C
    ...
    /* add inverse dependency */
    err_info = sr_lydmods_add_inv_data_dep(set2->set.d[0], sr_ly_leaf_value_str(sr_mod->child));
    ...
```
when trying to get set2->set.d[0]

Thanks.

**Comment by michalvasko** [comment]
Hi,
yep, there was a problem with installing all dependency modules in this case. It should work fine after updating *sysrepo*.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks, looks working better now!
