### ISSUE TITLE
[New sysrepo] sysrepocfg coredump during import

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#1737]
**Version:**
sysrepocfg -V
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.3.21 (SO v4.1.8)

**after install module, then import startup data**
/usr/local/bin/sysrepocfg --import=ietf-netconf-acm-startup.xml --datastore=startup --module=ietf-netconf-acm
[ERR]: Attribute prefix does not match any implemented schema in the context.
Segmentation fault (core dumped)

**gdb**
....
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/sysrepocfg --import=ietf-netconf-acm-startup.xml --datastore=sta'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f61285a66c2 in lyd_free_withsiblings () from /usr/local/lib/libyang.so.1
(gdb) bt
#0  0x00007f61285a66c2 in lyd_free_withsiblings () from /usr/local/lib/libyang.so.1
#1  0x00007f6128846917 in sr_modinfo_free (mod_info=0x7fff6dcd3d50) at /home/jimmy/shasta/apps_pub/sysrepo/src/modinfo.c:1906
#2  0x00007f612882e6a9 in _sr_replace_config (session=0x55b388e32bf0, ly_mod=0x55b388e52da0, src_config=0x7fff6dcd3da8, trg_datastore=SR_DS_STARTUP, timeout_ms=5000)
    at /home/jimmy/shasta/apps_pub/sysrepo/src/sysrepo.c:2478
#3  0x00007f612882e8cf in sr_replace_config (session=0x55b388e32bf0, module_name=0x7fff6dcd50d0 "ietf-netconf-acm", src_config=0x0, trg_datastore=SR_DS_STARTUP, timeout_ms=5000)
    at /home/jimmy/shasta/apps_pub/sysrepo/src/sysrepo.c:2522
#4  0x000055b387115480 in op_import (sess=0x55b388e32bf0, file_path=0x7fff6dcd5096 "ietf-netconf-acm-startup.xml", module_name=0x7fff6dcd50d0 "ietf-netconf-acm", format=LYD_UNKNOWN, not_strict=0)
    at /home/jimmy/shasta/apps_pub/sysrepo/src/executables/sysrepocfg.c:292
#5  0x000055b38711663e in main (argc=4, argv=0x7fff6dcd41d8) at /home/jimmy/shasta/apps_pub/sysrepo/src/executables/sysrepocfg.c:786
(gdb)

**Comment by jjin62** [comment]
not reproducible any more.
