### ISSUE TITLE
new sysrepo: crash on assertion when reading nc-notifications state data

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1770]
Versions:
- sysrepo fdevel
- libyang devel
- netopeer2-server 1.1.1
```
igort@igort-vb-mint:15:31:24:~/Perforce/OLT/aspen/main/build/host-sim/fs$ LD_LIBRARY_PATH=lib bin/netopeer2-server -V
netopeer2-server 1.1.1
compile time: Jan 21 2020, 13:04:36
igort@igort-vb-mint:15:31:38:~/Perforce/OLT/aspen/main/build/host-sim/fs$ LD_LIBRARY_PATH=lib bin/sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.49 (SO v4.2.7)
```
netopeer2-server crashes when client tries to read state data of nc-notifications module. The backtrace is below:

The reason appears to be that np2srv_ntf_get_data() function calls sr_get_module_info() which eventually calls sr_shmmain_conn_state_lock_update() to update a lock which already has read users.
Backtrace below. 
```
INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" with ID 1.
[INF]: SR: Processing "operational" "nc-notifications" event with ID 1.
netopeer2-server: /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1877: sr_shmmain_conn_state_lock_update: Assertion `conn_s->main_lock.mode == SR_LOCK_NONE' failed.

Thread 3 "netopeer2-serve" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff4194700 (LWP 31213)]
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6d79801 in __GI_abort () at abort.c:79
#2  0x00007ffff6d6939a in __assert_fail_base (fmt=0x7ffff6ef07d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff740f850 "conn_s->main_lock.mode == SR_LOCK_NONE", 
    file=file@entry=0x7ffff740eed0 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=line@entry=0x755, 
    function=function@entry=0x7ffff740fd20 <__PRETTY_FUNCTION__.8731> "sr_shmmain_conn_state_lock_update") at assert.c:92
#3  0x00007ffff6d69412 in __GI___assert_fail (assertion=0x7ffff740f850 "conn_s->main_lock.mode == SR_LOCK_NONE", 
    file=0x7ffff740eed0 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=0x755, 
    function=0x7ffff740fd20 <__PRETTY_FUNCTION__.8731> "sr_shmmain_conn_state_lock_update") at assert.c:101
#4  0x00007ffff73fa5e8 in sr_shmmain_conn_state_lock_update (conn=0x622c00, mode=SR_LOCK_NONE, lock=0x1) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1877
#5  0x00007ffff73fa961 in sr_shmmain_lock_remap (conn=0x622c00, mode=SR_LOCK_NONE, remap=0x0, lydmods=0x1, func=0x7ffff740a180 <__func__.8419> "sr_get_module_info")
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1979
#6  0x00007ffff73c90b8 in sr_get_module_info (conn=0x622c00, sysrepo_data=0x7ffff4193ae0) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:1519
#7  0x0000000000406a79 in np2srv_ntf_get_data (sr_conn=0x622c00) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/netopeer2/Netopeer2-1.1.1/server/main.c:108
#8  0x0000000000406d5a in np2srv_state_data_cb (UNUSED_session=0x7ffff4193c50, module_name=0x6445b0 "nc-notifications", path=0x64f570 "/nc-notifications:netconf", 
    UNUSED_request_xpath=0x7fffd4048960 "/nc-notifications:netconf", UNUSED_request_id=0x1, parent=0x7ffff4193c20, UNUSED_private_data=0x0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/netopeer2/Netopeer2-1.1.1/server/main.c:178
#9  0x00007ffff7404198 in sr_shmsub_oper_listen_process_module_events (oper_subs=0x63c0a0, conn=0x622c00) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2180
#10 0x00007ffff73ccdea in sr_process_events (subscription=0x65db30, session=0x0, stop_time_in=0x7ffff4193e20)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:2998
#11 0x00007ffff74061d6 in sr_shmsub_listen_thread (arg=0x65db30) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2925
#12 0x00007ffff7bbd6db in start_thread (arg=0x7ffff4194700) at pthread_create.c:463
#13 0x00007ffff6e5a88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 4
#4  0x00007ffff73fa5e8 in sr_shmmain_conn_state_lock_update (conn=0x622c00, mode=SR_LOCK_NONE, lock=0x1) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1877
1877	            assert(conn_s->main_lock.mode == SR_LOCK_NONE);
(gdb) p *conn_s
$1 = {conn_ctx = 0x622c00, pid = 0x79e8, main_lock = {mode = SR_LOCK_READ, rcount = 0x2}, mod_locks = 0x31b8, evpipes = 0x38c0, evpipe_count = 0x2}
(gdb) q
```

**Comment by igortern** [comment]
How to reproduce:
- build netopeer2-server. It will populate a few models in sysrepo. No other models are necessary
- connect from netopeer2-cli
- run "get" cli command

**Comment by michalvasko** [comment]
Hi,
sorry about that, it was the result of some recent changes not being handled correctly in every case. Should work now.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
It works.
Thanks,
Igor
