### ISSUE TITLE
sysrepod crash when sent a notification

### ISSUE THREAD

**Issue by jiantuo** [sysrepo/sysrepo#1909]
Hi Guys,

I enter a sysrepod crash issue when try to send hardware-state-oper-disabled notification defined in ietf-hardware.yang.

logs when sysrepod crash:
`VERBOSE: Session 1: thread 4 event new RPC.
[DBG] (cm_conn_read_cb:1179) fd 13 readable (revents 1)
[DBG] (cm_conn_read_cb:1192) 228 bytes of data received on fd 13
[DBG] (cm_conn_read_cb:1202) fd 13 would block
[DBG] (cm_conn_in_buff_process:1132) New message of size 224 bytes received.
[DBG] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=4, current count=1.
[DBG] (rp_msg_process:4207) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:3823) Thread id=140621019047680 signaled.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=5, count=0.
[DBG] (rp_event_notif_req_process:3060) Processing event notification request (/ietf-hardware:hardware-state-oper-disabled).
[DBG] (dm_get_data_info_internal:2795) Module ietf-hardware already loaded`

root@a2da64a0008c:/opt/dev/dbg_files# ps
  PID TTY          TIME CMD
   15 pts/1    00:00:00 bash
 4677 pts/1    00:00:00 sysrepo-plugind
 4685 pts/1    00:00:05 netopeer2-serve
 4710 pts/1    00:00:00 ps
root@a2da64a0008c:/opt/dev/dbg_files#`

I tried to gdb , however got "No symbol table info available".
`
Type "apropos word" to search for commands related to "word"...
Reading symbols from sysrepod...done.
[New LWP 4676]
[New LWP 4673]
[New LWP 4674]
[New LWP 4675]
[New LWP 4666]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `sysrepod -d -l4'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe4e588391b in dm_validate_procedure_content (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, di=0x7fe4cc1753a0, type=DM_PROCEDURE_EVENT_NOTIF, input=true, proc_node=0x7fe4dc05fe70,
    data_tree=0x7fe4e1e35bb8, ret_ctx=0x7fe4e1e35bc8) at /opt/dev/sysrepo/src/data_manager.c:6178
6178                if (node->next) {
[Current thread is 1 (Thread 0x7fe4e1e36700 (LWP 4676))]
(gdb)
(gdb) bt
#0  0x00007fe4e588391b in dm_validate_procedure_content (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, di=0x7fe4cc1753a0, type=DM_PROCEDURE_EVENT_NOTIF, input=true, proc_node=0x7fe4dc05fe70,
    data_tree=0x7fe4e1e35bb8, ret_ctx=0x7fe4e1e35bc8) at /opt/dev/sysrepo/src/data_manager.c:6178
#1  0x00007fe4e588630f in dm_validate_procedure (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, type=DM_PROCEDURE_EVENT_NOTIF, xpath=0x55c4acbf8770 "/ietf-hardware:hardware-state-oper-disabled",
    api_variant=SR_API_VALUES, args_p=0x7fe4d8119820, arg_cnt=2, input=true, sr_mem=0x0, with_def=0x7fe4e1e35d30, with_def_cnt=0x7fe4e1e35d58, with_def_tree=0x7fe4e1e35d40, with_def_tree_cnt=0x7fe4e1e35d60,
    res_data_tree=0x7fe4e1e35d18, res_ctx=0x7fe4e1e35d20) at /opt/dev/sysrepo/src/data_manager.c:6460
#2  0x00007fe4e588695d in dm_validate_event_notif (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, event_notif_xpath=0x55c4acbf8770 "/ietf-hardware:hardware-state-oper-disabled", values=0x7fe4d8119820,
    value_cnt=2, sr_mem=0x0, with_def=0x7fe4e1e35d30, with_def_cnt=0x7fe4e1e35d58, with_def_tree=0x7fe4e1e35d40, with_def_tree_cnt=0x7fe4e1e35d60, res_data_tree=0x7fe4e1e35d18, res_ctx=0x7fe4e1e35d20)
    at /opt/dev/sysrepo/src/data_manager.c:6544
#3  0x00007fe4e581def2 in rp_event_notif_req_process (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, msg=0x55c4acbf86a8, skip_msg_cleanup=0x7fe4e1e35e83) at /opt/dev/sysrepo/src/request_processor.c:3088
#4  0x00007fe4e582117e in rp_req_dispatch (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, msg=0x55c4acbf86a8, skip_msg_cleanup=0x7fe4e1e35e83) at /opt/dev/sysrepo/src/request_processor.c:3522
#5  0x00007fe4e5822460 in rp_msg_dispatch (rp_ctx=0x55c4acb15ac0, session=0x55c4acbdfc40, msg=0x55c4acbf86a8) at /opt/dev/sysrepo/src/request_processor.c:3669
#6  0x00007fe4e5822dff in rp_worker_thread_execute (rp_ctx_p=0x55c4acb15ac0) at /opt/dev/sysrepo/src/request_processor.c:3770
#7  0x00007fe4e555e6db in start_thread (arg=0x7fe4e1e36700) at pthread_create.c:463
#8  0x00007fe4e528788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`

core file and ietf-hardware.yang is attached.

My sysrepo is 0.7.4, it is quit old. If you have fixed this issue could you pls tell me the commit?

Thanks

[core.zip](https://github.com/sysrepo/sysrepo/files/4468693/core.zip)

[ietf-hardware.zip](https://github.com/sysrepo/sysrepo/files/4468388/ietf-hardware.zip)

**Comment by jiantuo** [comment]
fixed via compare with the latest code.
Thanks.
