### ISSUE TITLE
Performing a `set_item` during a `subscribe` loop

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2020]
I am getting a timeout error when running `set_item` while within a `subscribe` loop. 

My goal here is to subscribe to a module, and whenever a change is seen, I want to perform a separate calculation and run `set_item` to update the data in a leaf.

I am able to run `set_item` when it is the only session running, however when I try to run `set_item` within a session of a subscribe loop, the operation times out.

Here is a snippet of my code (it's adopted from [python_application_changes_example.py](https://github.com/sysrepo/sysrepo/blob/v1.4.58/bindings/python/examples/python_application_changes_example.py))
```
# Function to be called for subscribed client of given session whenever configuration changes.
count = 1
def module_change_cb(sess, module_name, xpath, event, request_id, private_data):
    try:
        print("\n\n ========== Notification " + ev_to_str(event) + " =============================================\n")
        if sr.SR_EV_CHANGE == event:
            print("\n ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========\n")
            print_current_config(sess, module_name);

        print("\n ========== CHANGES: =============================================\n")

        change_path = "/" + module_name + ":*//."

        it = sess.get_changes_iter(change_path);
        global count
        while True:
            change = sess.get_change_next(it)
            print("loop %d  - change %s" % (count, change))
            count += 1
            if change is None:
                break
            if sr.SR_EV_DONE == event:
                #!!!!!!!######## THIS IS WHERE THE PROBLEM HAPPENS#############!!!!!!!#
                if change.oper() == sr.SR_OP_MODIFIED:
                    print("Running subprocess")
                    subprocess.run(["python3", "rmbn_set_item.py", "/rmbn:rmbn-config/raw_hashCode", "9999", "sr.SR_INT32_T"])
                #!!!!!!!!!!######## THIS IS WHERE THE PROBLEM HAPPENS#############!!!!!!!!!#
                print_change(change.oper(), change.old_val(), change.new_val())
                #if change.oper() == sr.SR_OP_MODIFIED:
                    #x2 = sess.set_item_str("/rmbn:rmbn-config/raw_hashCode", "8888")
                    #print("x2 = %s" % x2)

        print("\n\n ========== END OF CHANGES =======================================\n")

    except Exception as e:
        print(e)

    return sr.SR_ERR_OK
```

Looking closer at this section I have:
```
            if sr.SR_EV_DONE == event:
                if change.oper() == sr.SR_OP_MODIFIED:
                    print("Running subprocess")
                    subprocess.run(["python3", "rmbn_set_item.py", "/rmbn:rmbn-config/raw_hashCode", "9999", "sr.SR_INT32_T"])
```

Where the `subprocess` is really the end point of my trying to create a new session and perform a set item. Here is my `set_item` code:
```
import sysrepo as sr
import sys

xpath = sys.argv[1]
val_str = sys.argv[2]
val_type = eval(sys.argv[3])

print("xpath = `%s`, val_str = `%s`, val_type = `%s`" % (xpath, val_str, val_type))

conn = sr.Connection(sr.SR_CONN_DEFAULT)
sess = sr.Session(conn)
v = sr.Val(val_str, val_type)
sess.set_item(xpath, v)
sess.apply_changes()
sess.session_stop()
```

In a previous iteration, I had this new session created directly within my main python script. 

Here is the error I get:
```
 ========== CHANGES: =============================================

loop 3  - change <sysrepo.Change; proxy of <Swig Object of type 'std::shared_ptr< sysrepo::Change > *' at 0x7efedd4c4ea0> >
Running subprocess
xpath = `/rmbn:rmbn-config/raw_hashCode`, val_str = `9999`, val_type = `15`
Traceback (most recent call last):
  File "rmbn_set_item.py", line 14, in <module>
    sess.apply_changes()
  File "/usr/lib64/python3.6/site-packages/sysrepo.py", line 2915, in apply_changes
    return _sysrepo.Session_apply_changes(self, timeout_ms, wait)
RuntimeError: Timeout expired
```

When I try to re-use the same session, I actually end up blowing up my netopeer server and sysrepo and I need to reboot my machine.

So again, my goal is to modify the data in a leaf while I am subscribed to modification events to the module. Here is my yang file in case you want to see it:
```
module rmbn {
  namespace "urn:com:txug:rmbn";
  prefix rmbn;

  container rmbn-config {
    config true;
    leaf raw {
      type string;
    }
    leaf raw_hashCode {
      type int32;
    }
    leaf processed {
      type boolean;
      default "false";
    }
  }
}
```

**Comment by michalvasko** [comment]
Hi,
I am not what you are trying to achieve but modifying data in the change callback is never a good a sign. But there is a special `SR_EV_UPDATE` event for this purpose.

Anyway, I do not know to what data you are subscribed but if it is the module `rmbn`, then it all makes sense. Because your callback is stuck waiting for the new changes to be applied but the new change causes this callback to be called again so you get a deadlock.

Also,the session in the callback is an implicit one so it does not support all API calls because it is intended only for a few ones. You can reset *sysrepo* state by calling `make shm_clean`, the effect should be exactly the same as a reboot.

Regards,
Michal

**Comment by esend7881** [comment]
Perhaps I should make a new github issue to explain my true, overaching goal but I'll write it out here anyway.

**My main goal is this:**
I am creating a system that, when a user submits a netconf `edit-config`, it will initiate a set of actions in my system that will atomically alter the configuration of our system and then submit a notification to the user of its success or failure.

Think of it as a big SQL transaction that, at the end, either commits or rolls back. 

So, steps

1. User submits an edit-config
2. System accepts config and works to implement this config
3. If the config is successful, sends by a thumbs up responce (not sure the formal way of doing this)
4. If the config is a failure, sends by a thumbs down response (and I will have to make sure the config is rolled back internally)
5. All this is done atomically. So, if a user submits two configs in a row, they won't conflict with each other.

We were thinking to go about this by accepting the `edit-config` and then, within sysrepo, we would edit parts of our leaves with the success or failure flags and they would happen within the same session as the initial change. We were hoping this would keep everything atomic; by doing edits outside of the session, multiple configuration changes could conflict with each other.

We weren't sure to go about this with pure netconf or to leverage sysrepo directly. We noticed all these plugins made for sysrepo and figured those could be used directly to talk to our datastore.

Our system is:

- netopeer 1.1.27
- sysrepo 1.4.58
- libyang 1.0.167
- libnetconf2 1.1.24

**Comment by michalvasko** [comment]
Hi,
okay, this should be one of the primary functions of *sysrepo*.

1. `edit-config` is received, either through NETCONF of directly in *sysrepo*, it makes no difference.
2. Your subscribed callbacks are called accordingly with `SR_EV_CHANGE` event with broken-down changes that should make applying them as simple as possible.
3. On success you return `SR_ERR_OK` from all the callbacks, you are done.
4. On error you return an error value from a callback, possibly with a specific error message set. In that case all the callbacks that were already applied successfully are called again with `SR_EV_ABORT` event and reversed changes so ideally you can simply keep applying the changes, which will, in effect, revert them.
5. All this is happening during `sr_apply_changes()`, which blocks other similar calls on data with an intersection. Meaning atomicity is ensured because colliding requests are serialized.

Regards,
Michal

**Comment by esend7881** [comment]
> Hi,
> okay, this should be one of the primary functions of _sysrepo_.
> 
> 1. `edit-config` is received, either through NETCONF of directly in _sysrepo_, it makes no difference.
> 2. Your subscribed callbacks are called accordingly with `SR_EV_CHANGE` event with broken-down changes that should make applying them as simple as possible.
> 3. On success you return `SR_ERR_OK` from all the callbacks, you are done.
> 4. On error you return an error value from a callback, possibly with a specific error message set. In that case all the callbacks that were already applied successfully are called again with `SR_EV_ABORT` event and reversed changes so ideally you can simply keep applying the changes, which will, in effect, revert them.
> 5. All this is happening during `sr_apply_changes()`, which blocks other similar calls on data with an intersection. Meaning atomicity is ensured because colliding requests are serialized.
> 
> Regards,
> Michal

Thank you! I will experiment with this

**Comment by esend7881** [comment]
> You can reset _sysrepo_ state by calling `make shm_clean`, the effect should be exactly the same as a reboot.
> 
> Regards,
> Michal

Actually - am noticing that `make shm_clean` is not working in cleaning up if I mess up sysrepo and it doesn't ext with SR_ERR_OK/SR_EV_ABORT. I.e., if my python script doesn't return either of those two value, but my script dies nonetheless, I still need to reboot my system and restart all my processes to get sysrepo going.

Is there another clean up command that will reset the state of sysrepo?

**Comment by michalvasko** [comment]
Hi,
right, to get the same effect as reboot you need to stop all other *sysrepo* processes when calling `make shm_clean`, I left that out. However, even if your plugin crashes, *sysrepo* should continue to work. But to clean up after the crashed client a state is required with no *sysrepo* connection, the cleanup then occurs on creating the first new connection. And if you have many simultaneous clients, it may never happen. But that should only mean you constantly get timeouts for changes that the crashed client was subscribed for so *sysrepo* still works (no more crashes or anything like that).

Regards,
Michal

**Comment by esend7881** [comment]
> Hi,
> right, to get the same effect as reboot you need to stop all other _sysrepo_ processes when calling `make shm_clean`
> 
> Regards,
> Michal

What is the command to force stop all _sysrepo_ processes? I try looking at `ps aux` but can't seem to figure out what is sysrepo or not?

**Comment by michalvasko** [comment]
Hi,
there is no command but there could be one added, theoretically. If you request `sysrepo-monitoring` data, you will see all the process PIDs in a list, so you can use that. But I think you should know them even without that.

Regards,
Michal

**Comment by esend7881** [comment]
Michal,
I'm at that point now where sysrepo is "between states" and I have to either reboot or figure out how to manually reset sysrepo. I am looking at the data inside of `sysrepo-monitoring` but not seeing anything in there.

![image](https://user-images.githubusercontent.com/5004148/84686987-c98c7c00-aef1-11ea-8f76-e097cb7ed137.png)

Is there another way to find any pid related to sysrepo? Perhaps I could grep through `ps aux` and find it with the right search pattern?

**Comment by esend7881** [comment]
You know what - I think I found it. I parsed through every element in sysrepo and only found one PID, the PID of netopeer-server. I killed netopeer-server, then ran `make shm_clean` and it appears to work now, in that sysrepo reset without a reboot.

I am wondering, in a production environment, how does one keep sysrepo resilient against these between-state behaviors? I.e., if my sysrepo were to freeze up like this in production, do people just reboot the system? 

I wouldn't mind programming a way for my system to detect sysrepo is timing out and then, gracefully, reset sysrepo back to life. I'd prefer not to just kill netopeer-server and re-run the make command, but does something like this already exist?

**Comment by michalvasko** [comment]
Hi,
firstly, you could have mentioned that you are using the GUI and secondly, *sysrepo-monitoring* includes only state data so you will not see any in the configuration.

Now, *netopeer2-server* is the most obvious *sysrepo* client so you definitely cannot have that running when you do `make shm_clean`. But this is not a solution, it is just a way of making it work again after something goes wrong. Generally, *sysrepo* should be quite robust and be able to work even after an application crashed or something similar. I would need to know much more details about what you are doing and what goes wrong to try and fix it so that no *sysrepo* "reset" is needed.

Regards,
Michal
