### ISSUE TITLE
sr_copy_config segfault with SR_CONN_CACHE_RUNNING

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#2077]
Hi,

I got a segmentation fault in _sr_copy_config()_ when _SR_CONN_CACHE_RUNNING_ flag is enabled on the connection:

```
Program received signal SIGSEGV, Segmentation fault.
0xf79905d3 in sr_ly_link (first=0x7, sibling=0x7) at /opt/dev/sysrepo/src/common.c:3189
3189	/opt/dev/sysrepo/src/common.c: No such file or directory.
(gdb) bt
#0  0xf79905d3 in sr_ly_link (first=0x7, sibling=0x7) at /opt/dev/sysrepo/src/common.c:3189
#1  0xf79985ef in sr_modinfo_module_data_load (mod_info=0xffffcabc, mod=0xf4b03f50, sid=0x0, request_xpath=0x0, timeout_ms=0, opts=0, cb_error_info=0x0) at /opt/dev/sysrepo/src/modinfo.c:1434
#2  0xf7999967 in sr_modinfo_data_load (mod_info=0xffffcabc, mod_type=7 '\a', cache=0, sid=0x0, request_xpath=0x0, timeout_ms=0, opts=0, cb_error_info=0x0) at /opt/dev/sysrepo/src/modinfo.c:1916
#3  0xf7982e12 in _sr_replace_config (session=0xf5f2a940, ly_mod=0x0, src_config=0xffffcb38, timeout_ms=60000, wait=1) at /opt/dev/sysrepo/src/sysrepo.c:2545
#4  0xf798333c in sr_copy_config (session=0xf5f2a940, module_name=0x0, src_datastore=SR_DS_STARTUP, timeout_ms=60000, wait=1) at /opt/dev/sysrepo/src/sysrepo.c:2684
#5  0x56555c39 in main (argc=1, argv=0xffffcd04) at test.c:32
```

It can be reproduced easily with the following example code, using an empty startup database:

```
int main(int argc, char **argv) {
  sr_conn_ctx_t *connection = NULL;
  sr_session_ctx_t *session = NULL;
  int rc = SR_ERR_OK;

  /* turn logging on */
  sr_log_stderr(SR_LL_WRN);

  /* connect to sysrepo */
  rc = sr_connect(SR_CONN_CACHE_RUNNING, &connection);
  if (rc != SR_ERR_OK) {
    exit(1);
  }

  /* start session */
  rc = sr_session_start(connection, SR_DS_RUNNING, &session);
  if (rc != SR_ERR_OK) {
    exit(1);
  }

  rc = sr_copy_config(session, NULL, SR_DS_STARTUP, 60000, 1);
  if (rc != SR_ERR_OK) {
    printf("sr_copy_config error: %s\n", sr_strerror(rc));
    exit(1);
  }
  printf("Copy success\n");

  return 0;
}
```

Note that the issue is not present on sysrepo version 1.4.72 and below.

sysrepo version: 1.4.73
libyang version: 1.0.186

Thanks!

**Comment by michalvasko** [comment]
Hi,
right, should no longer crash.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the bugfix, it worked!
