### ISSUE TITLE
Assertion failed in sr_module_change_subscribe

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2244]
Hi,

I have multiple applications:

- application 1: registered for ietf-interfaces with priority 2
- application 2: registered for ietf-interfaces with priority 1
- one other application changes config in ietf-interfaces

I met an assertion failure when application 1 tried to register a new config change callback with **sr_module_change_subscribe**() while the process's event handler was busy:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f0a77152921 in __GI_abort () at abort.c:79
#2  0x00007f0a7714248a in __assert_fail_base (fmt=0x7f0a772c9750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f0a77553c9e "0", 
    file=file@entry=0x7f0a77553c80 "/opt/dev/sysrepo/src/common.c", line=line@entry=242, function=function@entry=0x7f0a77555000 <__PRETTY_FUNCTION__.9059> "sr_sub_change_del") at assert.c:92
#3  0x00007f0a77142502 in __GI___assert_fail (assertion=0x7f0a77553c9e "0", file=0x7f0a77553c80 "/opt/dev/sysrepo/src/common.c", line=242, function=0x7f0a77555000 <__PRETTY_FUNCTION__.9059> "sr_sub_change_del")
    at assert.c:101
#4  0x00007f0a7751707c in sr_sub_change_del (mod_name=0x55fcdf9f077b "ietf-interfaces", xpath=0x55fcdf9f0750 "/ietf-interfaces:interfaces/interface/type", ds=SR_DS_RUNNING, 
    change_cb=0x55fcdf9eff78 <interfaces_change_cb>, private_data=0x4, priority=2, sub_opts=8, subs=0x55fce1765500) at /opt/dev/sysrepo/src/common.c:242
#5  0x00007f0a775118c8 in sr_module_change_subscribe (session=0x55fce1764790, module_name=0x55fcdf9f077b "ietf-interfaces", xpath=0x55fcdf9f0750 "/ietf-interfaces:interfaces/interface/type", 
    callback=0x55fcdf9eff78 <interfaces_change_cb>, private_data=0x4, priority=2, opts=11, subscription=0x7ffe1a200ab8) at /opt/dev/sysrepo/src/sysrepo.c:3485
```

I attached example applications with script to reproduce the issue.
[assert_failure.zip](https://github.com/sysrepo/sysrepo/files/5644106/assert_failure.zip)

In short the following happens here:

- "subscribe": registered for ietf-interfaces with priority 2
- "subscribe2": registered for ietf-interfaces with priority 1
- "change_config": changes config in ietf-interfaces
- "subscribe": event handler thread is blocked and DONE for ietf-interfaces is waiting to be processed
- "subscribe": tries to register an other callbnack for ietf-interfaces which fails with timeout
- "change_config": sr_apply_changes timeout
- "subscribe": event handler gets unblocked
- "subscribe": tries to register the callback again
- "subscribe": DONE handler is invoked and blocked
- "subscribe": "sr_sub_change_add: Connection timed out" error
- "subscribe": DONE handler gets unblocked and assert failure happens

The output of script:

```
./script.sh
***** Starting subscribe
./subscribe
./subscribe: [INF]: Applying scheduled changes.
./subscribe: [INF]: No scheduled changes.
./subscribe: [INF]: Datastore copied from <startup> to <running>.
./subscribe: [INF]: Session 1 (user "devuser") created.
./subscribe: [INF]: There are no subscribers for changes of the module "ietf-interfaces" in running DS.
./subscribe: sr_apply_changes OK
./subscribe: event_handler waiting for USR2 signal...
***** Starting subscribe(2)
./subscribe2
./subscribe2: [INF]: Scheduled changes not applied because of other existing connections.
./subscribe2: [INF]: Session 2 (user "devuser") created.
***** Change eth0
./change_config eth0
./change_config: [INF]: Scheduled changes not applied because of other existing connections.
./change_config: [INF]: Session 3 (user "devuser") created.
./subscribe2: [INF]: Processing "ietf-interfaces" "change" event with ID 1 priority 1 (remaining 1 subscribers).
./change_config: sr_apply_changes(eth0)...
./subscribe2: [INF]: Successful processing of "change" event with ID 1 priority 1 (remaining 0 subscribers).
./change_config: [INF]: Published event "change" "ietf-interfaces" with ID 1 priority 1 for 1 subscribers.
./change_config: [INF]: Event "change" with ID 1 priority 1 succeeded.
./change_config: [INF]: Published event "done" "ietf-interfaces" with ID 1 priority 2 for 1 subscribers.
./subscribe: sr_module_change_subscribe...
./change_config: [ERR]: Callback event "done" with ID 1 processing timed out.
./subscribe: [ERR]: Waiting on a conditional variable failed (sr_module_change_subscribe: Connection timed out).
./subscribe: sr_module_change_subscribe error, retry later
./change_config: [ERR]: Locking subscription of "ietf-interfaces" failed, previous event "done" with ID 1 was not processed.
./change_config: sr_apply_changes(eth0) error, rc=13
Sending USR2 to subscribe
./subscribe: SIGUSR2 received
./subscribe: sr_module_change_subscribe...
./subscribe: event_handler ..done
./subscribe: [INF]: Processing "ietf-interfaces" "done" event with ID 1 priority 2 (remaining 1 subscribers).
./subscribe: interfaces_change_cb waiting for USR2 signal...
./subscribe: [ERR]: Locking a mutex failed (sr_sub_change_add: Connection timed out).
Sending USR2 to subscribe
./subscribe: SIGUSR2 received
./subscribe: interfaces_change_cb ..done
./subscribe: [INF]: Successful processing of "done" event with ID 1 priority 2 (remaining 0 subscribers).
./subscribe: subscribe: /opt/dev/sysrepo/src/common.c:242: sr_sub_change_del: Assertion `0' failed.
Assert failure detected

```

sysrepo version: 1.4.92
libyang version: 1.0.20

Thanks!

**Comment by michalvasko** [comment]
When fixing #2243 I also did some minor cleanup which I think have fixed this because I cannot reproduce this anymore with the latest version.

**Comment by awesomenode** [comment]
I cannot reproduce it on the latest version.
Thanks!
