### ISSUE TITLE
sysrepocfg CPU hog with 100K interfaces on libyang2 branch 

### ISSUE THREAD

**Issue by Reshad-Rahman** [sysrepo/sysrepo#2277]
I am using the same example as in #2268 (see c_xml_yang.zip in that issue), only change is that all nodes are `config true`. 

With 10K interfaces, all is good:
```
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ time sysrepocfg -X -x /ex-interface:interfaces/interface[name=\'eth9999\']  
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth9999</name>
    <hw_index>9999</hw_index>
    <sw_index>9999</sw_index>
  </interface>
</interfaces>

real    0m0.044s
user    0m0.033s
sys     0m0.007s
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ time sysrepocfg -X -x /ex-interface:interfaces/interface[hw_index=9999]    
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth9999</name>
    <hw_index>9999</hw_index>
    <sw_index>9999</sw_index>
  </interface>
</interfaces>

real    0m0.062s
user    0m0.049s
sys     0m0.007s
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$
```

However with 100K interfaces:
```
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ time sysrepocfg -X -x /ex-interface:interfaces/interface[name=\'eth99999\'] 
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth99999</name>
    <hw_index>99999</hw_index>
    <sw_index>99999</sw_index>
  </interface>
</interfaces>

real    0m0.306s
user    0m0.267s
sys     0m0.029s
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ time sysrepocfg -X -x /ex-interface:interfaces/interface[hw_index=99999] 
<hangs forever>

top - 00:27:24 up  2:00,  6 users,  load average: 1.01, 1.07, 1.07
Tasks: 145 total,   3 running, 142 sleeping,   0 stopped,   0 zombie
%Cpu(s): 48.4 us,  0.3 sy,  0.0 ni, 51.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0
MiB Mem :   1995.2 total,    520.8 free,    548.3 used,    926.1 buff/cache
MiB Swap:   1953.0 total,   1953.0 free,      0.0 used.   1247.3 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2263 vagrant      20   0   79176  76884   3376 R 100.0   3.8  31:15.32 sysrep+
<snip>

(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x00007f5aea960444 in __GI___libc_malloc (bytes=32) at malloc.c:3050
3050    in malloc.c
(gdb) bt
#0  0x00007f5aea960444 in __GI___libc_malloc (bytes=32) at malloc.c:3050
#1  0x00007f5aeab3ff85 in set_insert_node (set=0x7fffc8b48d30, node=0xfbf6b0, pos=0, 
    node_type=LYXP_NODE_NONE, idx=0) at /home/vagrant/dev/libyang2/src/xpath.c:1155
#2  0x00007f5aeab4851e in eval_predicate (exp=0xc1df60, tok_idx=0x7fffc8b4906e, 
    set=<optimized out>, options=1, parent_pos_pred=1 '\001')
    at /home/vagrant/dev/libyang2/src/xpath.c:6742
#3  0x00007f5aeab47744 in eval_name_test_with_predicate (exp=<optimized out>, 
    tok_idx=<optimized out>, attr_axis=<optimized out>, all_desc=<optimized out>, 
    set=<optimized out>, options=<optimized out>)
    at /home/vagrant/dev/libyang2/src/xpath.c:7192
#4  eval_relative_location_path (exp=<optimized out>, tok_idx=<optimized out>, 
    all_desc=<optimized out>, set=<optimized out>, options=<optimized out>)
    at /home/vagrant/dev/libyang2/src/xpath.c:7346
#5  0x00007f5aeab40158 in eval_path_expr (exp=<optimized out>, tok_idx=<optimized out>, 
    set=<optimized out>, options=<optimized out>)
    at /home/vagrant/dev/libyang2/src/xpath.c:7731
#6  eval_expr_select (exp=0xc1df60, tok_idx=0x7fffc8b4906e, etype=<optimized out>, 
    set=0x7fffc8b490e0, options=1) at /home/vagrant/dev/libyang2/src/xpath.c:8405
#7  0x00007f5aeab3fe86 in lyxp_eval (exp=0xc1df60, cur_mod=0x0, format=LY_PREF_JSON, 
    prefix_data=<optimized out>, ctx_node=0xc11020, tree=<optimized out>, 
    set=0x7fffc8b490e0, options=1) at /home/vagrant/dev/libyang2/src/xpath.c:8495
#8  0x00007f5aeaadd225 in lyd_find_xpath (ctx_node=0xc11020, xpath=<optimized out>, 
    set=0x7fffc8b49230) at /home/vagrant/dev/libyang2/src/tree_data.c:3494
#9  0x00007f5aeabb5261 in sr_modinfo_get_filter (mod_info=0x7fffc8b49250, 
    xpath=<optimized out>, session=<optimized out>, result=<optimized out>)
    at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/modinfo.c:1891
#10 0x00007f5aeaba2ecf in sr_get_data (session=0xc2b770, xpath=<optimized out>, 
    max_depth=<optimized out>, timeout_ms=5000, opts=<optimized out>, 
    data=<optimized out>) at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/sysrepo.c:1822
--Type <RET> for more, q to quit, c to continue without paging--
#11 0x00000000004034b0 in op_export (sess=0xc2b770, file_path=<optimized out>, 
    module_name=0x0, 
    xpath=0x7fffc8b4b863 "/ex-interface:interfaces/interface[hw_index=99999]", 
    format=LYD_XML, max_depth=<optimized out>, wd_opt=0, timeout_s=0)
    at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/executables/sysrepocfg.c:373
#12 0x0000000000403016 in main (argc=4, argv=0x7fffc8b49778)
    at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/executables/sysrepocfg.c:904
(gdb) frame 1
#1  0x00007f5aeab3ff85 in set_insert_node (set=0x7fffc8b48d30, node=0xfbf6b0, pos=0, 
    node_type=LYXP_NODE_NONE, idx=0) at /home/vagrant/dev/libyang2/src/xpath.c:1155
1155            set->val.nodes = malloc(LYXP_SET_SIZE_START * sizeof *set->val.nodes);
(gdb)
(gdb) info br
Num     Type           Disp Enb Address            What
2       breakpoint     keep y   0x00007f5aeab3ff89 in set_insert_node 
                                                   at /home/vagrant/dev/libyang2/src/xpath.c:1156
        breakpoint already hit 25852 times
        silent
        c
(gdb) 
```

```
vagrant@libyang2-vm:~/dev/libyang2/build$ git log 
commit b4239c9b00abd2c2520823f9f93a0724244998e3 (HEAD -> libyang2, origin/libyang2)
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Tue Jan 5 11:30:03 2021 +0100

    doc BUGFIX language name

commit ae6bba2f1867e79eb1be63bc32a1a93ec1e73b63
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Tue Jan 5 11:26:54 2021 +0100

    doc FEATURE mention RUST bindings project


vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ git log
commit eccf402f362891e60fa6b8f9bb33f522476dfc14 (HEAD -> libyang2, origin/libyang2)
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Tue Aug 11 13:45:45 2020 +0200

    sysrepo REFACTOR initial libyang2 support

commit b4f08a4aad8e2a871623d9ce99c129904727de3d
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Fri Dec 11 11:59:08 2020 +0100

    build BUGFIX valgrind environment vars name typo

```

**Comment by michalvasko** [comment]
Right, I thought this has already been fixed. In any case, should work now.

**Comment by Reshad-Rahman** [comment]
It does work after updating libyang. However (different issue) I didn't expect the duplicate entries in the output below when using /name and /*

```
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ sysrepocfg -X -x /ex-interface:interfaces/interface[hw_index=99999]/sw_index
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth99999</name>
    <sw_index>99999</sw_index>
  </interface>
</interfaces>
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ sysrepocfg -X -x /ex-interface:interfaces/interface[hw_index=99999]/name
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth99999</name>
    <name>eth99999</name>
  </interface>
</interfaces>
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ sysrepocfg -X -x /ex-interface:interfaces/interface[hw_index=99999]/*
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth99999</name>
    <name>eth99999</name>
  </interface>
  <interface>
    <name>eth99999</name>
    <hw_index>99999</hw_index>
    <sw_index>99999</sw_index>
  </interface>
</interfaces>
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$
```

**Comment by michalvasko** [comment]
Okay, you should not longer get duplicate keys (if you update *libyang*) but the results may still sometimes be not as you expect. Before asking again, please read through the issue #2210.

**Comment by Reshad-Rahman** [comment]
All good.
