### ISSUE TITLE
sr_set_item_str() crash in libyang2 branch

### ISSUE THREAD

**Issue by Reshad-Rahman** [sysrepo/sysrepo#2278]
Using the same example YANG as in #2268 (except that nodes are `config true`), trying to create a new list entry without the predicate form causes a crash (see fault). This works in `devel` branch.

```
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ ./examples/sr_set_item_example /ex-interface:interfaces/interface/name eth100000               
Application will set "/ex-interface:interfaces/interface/name" to "eth100000".
Segmentation fault
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ sudo ./examples/sr_set_item_example /ex-interface:interfaces/ex-interface:interface/ex-interface:name eth100000    
Application will set "/ex-interface:interfaces/ex-interface:interface/ex-interface:name" to "eth100000".
[WRN]: Cleaning up after a non-existent sysrepo client with CID 17.
Segmentation fault

Program received signal SIGSEGV, Segmentation fault.
sr_edit_add (session=0x441da0, 
    xpath=0x7fffffffe80c "/ex-interface:interfaces/interface/name", 
    value=<optimized out>, operation=0x7ffff7fac4aa "merge", 
    def_operation=0x7ffff7fac4aa "merge", position=0x0, keys=0x0, val=0x0, origin=0x0, 
    isolate=0) at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/edit_diff.c:2403
2403            for (parent = node; parent->parent; parent = lyd_parent(parent));
(gdb) print parent
$1 = (struct lyd_node *) 0x0
(gdb) print node
$2 = (struct lyd_node *) 0x0
(gdb) bt
#0  sr_edit_add (session=0x441da0, 
    xpath=0x7fffffffe80c "/ex-interface:interfaces/interface/name", 
    value=<optimized out>, operation=0x7ffff7fac4aa "merge", 
    def_operation=0x7ffff7fac4aa "merge", position=0x0, keys=0x0, val=0x0, origin=0x0, 
    isolate=0) at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/edit_diff.c:2403
#1  0x00007ffff7f7e218 in sr_set_item_str (session=0x441da0, path=<optimized out>, 
    value=<optimized out>, origin=<optimized out>, opts=<optimized out>)
    at /home/vagrant/dev/sysrepo-libyang2-Jan6/src/sysrepo.c:1977
#2  0x0000000000401216 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/vagrant/dev/sysrepo-libyang2-Jan6/examples/sr_set_item_example.c:59
```

```
vagrant@debian10:~/dev/sysrepo/build$ sysrepocfg -X -x /ex-interface:interfaces/interface[name=\'eth100000\']
vagrant@debian10:~/dev/sysrepo/build$ ./examples/sr_set_item_example /ex-interface:interfaces/ex-interface:interface/ex-interface:name eth100000
Application will set "/ex-interface:interfaces/ex-interface:interface/ex-interface:name" to "eth100000" in "running" datastore.
vagrant@debian10:~/dev/sysrepo/build$ sysrepocfg -X -x /ex-interface:interfaces/interface[name=\'eth100000\']
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth100000</name>
  </interface>
</interfaces>
vagrant@debian10:~/dev/sysrepo/build$ 
```

**Comment by michalvasko** [comment]
Right, should not longer crash but print an error instead. It is redundant to keep all these multiple inputs getting you the same functionality, you must use a predicate in this case.

**Comment by Reshad-Rahman** [comment]
Looks good

```
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ ./examples/sr_set_item_example /ex-interface:interfaces/ex-interface:interface/ex-interface:name eth100000
Application will set "/ex-interface:interfaces/ex-interface:interface/ex-interface:name" to "eth100000".
[WRN]: Cleaning up after a non-existent sysrepo client with CID 13.
[ERR]: Predicate missing for list "interface" in path "/ex-interface:interfaces/ex-interface:interface/ex-interface:name". (path: Schema location /ex-interface:interfaces/interface.)
[ERR]: Invalid datastore edit.
```
