### ISSUE TITLE
Segmentation fault in sr_shmsub_notify_wait_wr

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2321]
Hi,

I tested the latest version with lock remap fix, but I still have segmentation faults on my PowerPC based system:

```
#3  0x0f9a6178 in sr_shmsub_notify_wait_wr (sub_shm=0x48d43018, sub_shm@entry=0x48d43000, expected_ev=expected_ev@entry=SR_SUB_EV_NONE, timeout_ms=timeout_ms@entry=120000, cid=1232070040, cid@entry=7, 
    shm_data_sub=shm_data_sub@entry=0x496fe5e8, cb_err_info=0x80, cb_err_info@entry=0x496fe614)
    at sysrepo-1.4.110/src/shm_sub.c:326
#4  0x0f9a8068 in sr_shmsub_change_notify_change_done (mod_info=mod_info@entry=0x496fe7d0, sid=..., timeout_ms=timeout_ms@entry=120000)
    at sysrepo-1.4.110/src/shm_sub.c:1225
#5  0x0f973998 in sr_changes_notify_store (mod_info=mod_info@entry=0x496fe7d0, session=session@entry=0x1023b150, timeout_ms=timeout_ms@entry=120000, cb_err_info=cb_err_info@entry=0x496fe7fc)
    at sysrepo-1.4.110/src/sysrepo.c:2054
#6  0x0f978c9c in sr_apply_changes (session=0x1023b150, timeout_ms=120000, wait=<optimized out>)
    at sysrepo-1.4.110/src/sysrepo.c:2123
```

It seems that _multi_sub_shm_ is still remapped in _sr_shmsub_change_notify_change_done()_, which causes the segmentation fault on the shared, robust `sub_shm->lock.mutex`.

sysrepo version: 1.4.110
libyang version: 1.0.218

Thanks!

**Comment by michalvasko** [comment]
Yes, sorry about that, I forgot to remove it at this one place (I hope it is the only one).
