### ISSUE TITLE
Segmentation fault in sr_module_oper_data_dup_enabled

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2326]
Hi,

I have segmentation fault when calling `sr_get_item`:

```
Thread 3 "test" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3efe700 (LWP 7637)]
0x00007ffff7b8ec2b in sr_module_oper_data_dup_enabled (data=0x7fffec003900, ext_shm_addr=0x7ffff7fe6000 "\b", opts=opts@entry=0, enabled_mod_data=enabled_mod_data@entry=0x7ffff3efdc58, mod=<optimized out>, 
    mod=<optimized out>) at /opt/dev/sysrepo/src/modinfo.c:829
829	            if (!shm_changesubs[i].xpath && !(shm_changesubs[i].opts & SR_SUBSCR_PASSIVE)) {
(gdb) bt
#0  0x00007ffff7b8ec2b in sr_module_oper_data_dup_enabled (data=0x7fffec003900, ext_shm_addr=0x7ffff7fe6000 "\b", opts=opts@entry=0, enabled_mod_data=enabled_mod_data@entry=0x7ffff3efdc58, mod=<optimized out>, 
    mod=<optimized out>) at /opt/dev/sysrepo/src/modinfo.c:829
#1  0x00007ffff7b902be in sr_modinfo_module_data_load (cb_error_info=0x7ffff3efddb0, opts=0, timeout_ms=30000, request_xpath=0x555555555278 "/ietf-interfaces:interfaces/interface[name='eth1']/oper-status", 
    sid=..., mod=0x7fffec001410, mod_info=0x7ffff3efde40) at /opt/dev/sysrepo/src/modinfo.c:1612
#2  sr_modinfo_data_load (mod_info=mod_info@entry=0x7ffff3efde40, cache=cache@entry=4, sid=..., 
    request_xpath=request_xpath@entry=0x555555555278 "/ietf-interfaces:interfaces/interface[name='eth1']/oper-status", timeout_ms=timeout_ms@entry=30000, opts=0, cb_error_info=0x7ffff3efddb0)
    at /opt/dev/sysrepo/src/modinfo.c:1813
#3  0x00007ffff7b91745 in sr_modinfo_add_modules (mod_info=mod_info@entry=0x7ffff3efde40, mod_set=mod_set@entry=0x7ffff3efde30, mod_deps=<optimized out>, mod_deps@entry=0, mod_lock=mod_lock@entry=SR_LOCK_READ, 
    mi_opts=mi_opts@entry=68, sid=..., request_xpath=request_xpath@entry=0x555555555278 "/ietf-interfaces:interfaces/interface[name='eth1']/oper-status", timeout_ms=30000, get_opts=0)
    at /opt/dev/sysrepo/src/modinfo.c:1899
#4  0x00007ffff7b7c39c in sr_get_item (session=0x7fffec000b20, path=0x555555555278 "/ietf-interfaces:interfaces/interface[name='eth1']/oper-status", timeout_ms=30000, value=0x7ffff3efdee0)
    at /opt/dev/sysrepo/src/sysrepo.c:1376
#5  0x0000555555554de3 in get_thread_fn (ptr=0x0) at test.c:53
```

I attached a test application, which crashes in a short time.
[test.zip](https://github.com/sysrepo/sysrepo/files/5988276/test.zip)

It does the following in infinite loop:
- **thread1**: _sr_get_item()_ for config and pushed oper data
- **thread2**: subscribe for config and pushed oper data, then unsubscribe

libyang version: 1.0.221
sysrepo version: 1.4.113

Thanks!

**Comment by michalvasko** [comment]
Right, thanks for the nice test to reproduce. There were completely missing locks at one function after the recent changes and it should be fine now.
