### ISSUE TITLE
sr_module_change_subscribe(): too many open files

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2333]
Hi,

I encountered a "_Too many open files_" error when tried to register for operational data using `sr_module_change_subscribe()`.
I attached the test which registers and unregisters callback in infinite loop.
[test.zip](https://github.com/sysrepo/sysrepo/files/6004539/test.zip)

```
[ERR]: Failed to create "/dev/shm/srsub_ietf-interfaces.operational" SHM (Too many open files).
[ERR]: Opening "/etc/sysrepo/sr_evpipe1013" for writing failed (Too many open files).
 
Thread 1 "test" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff77c0921 in __GI_abort () at abort.c:79
#2  0x0000555555554d93 in main (argc=1, argv=0x7fffffffdad8) at test.c:111
```
 
Installed YANG modules:

- ietf-interfaces
- iana-if-type

 
sysrepo version: 1.4.115
libyang version: 1.0.221

Thanks!

**Comment by michalvasko** [comment]
I commented what is wrong with this example.

```C
while (!exit_application) {
    sr_subscription_ctx_t *tmp_sub = NULL;

    rc = sr_session_switch_ds(session, SR_DS_RUNNING);
    if (rc != SR_ERR_OK) {
        abort();
    }

    rc = sr_module_change_subscribe(session,
        "ietf-interfaces",
        "/ietf-interfaces:interfaces/interface[name='eth1']/description",
        module_change_cb,
        NULL,
        0,
        SR_SUBSCR_DONE_ONLY | SR_SUBSCR_PASSIVE,
        &tmp_sub);
    if (rc != SR_ERR_OK) {
      abort();
    }

    rc = sr_session_switch_ds(session, SR_DS_OPERATIONAL);
    if (rc != SR_ERR_OK) {
        abort();
    }

    /* causes tmp_sub to "leak", use SR_SUBSCR_CTX_REUSE in this call to fix */
    rc = sr_module_change_subscribe(session,
        "ietf-interfaces",
        "/ietf-interfaces:interfaces/interface[name='eth1']/oper-status",
        module_change_cb,
        NULL,
        0,
        SR_SUBSCR_DONE_ONLY | SR_SUBSCR_PASSIVE,
        &tmp_sub);
    if (rc != SR_ERR_OK) {
      abort();
    }

    sr_unsubscribe(tmp_sub);
    if (rc != SR_ERR_OK) {
      abort();
    }
  }
```

**Comment by awesomenode** [comment]
You are right, it was my fault, I missed the SR_SUBSCR_CTX_REUSE flag.
Thanks!
