### ISSUE TITLE
Regression: Failed to find matching hash for a child of XXX on latest devel

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2341]
I'm trying to update the NETCONF/YANG stack, and [this test case of our project that uses the IETF firewall module](https://github.com/CESNET/velia/blob/master/tests/sysrepo-firewall.cpp) hits an error:
```
libyang[0]: Failed to find matching hash for a child of "acls". (path: /ietf-access-control-list:acls)
```
I wanted to look at the installed YANG models to make this reproducible, but even `sysrepoctl --list` fails now. Here's the backtrace (from `sysrepoctl --list`):
```gdb
(gdb) r
Starting program: /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --list
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/3wa1xwnfv8ada1za1r8m4vmsiz1jifqq-glibc-2.32-35/lib/libthread_db.so.1".

Breakpoint 1, lyb_parse_schema_hash (sparent=0x6082d0, mod=mod@entry=0x0, data=0x7ffff7a58045 "", data@entry=0x7ffff7a58044 "\224", yang_data_name=yang_data_name@entry=0x0, options=options@entry=8705, snode=snode@entry=0x7ffffffe6b50, lybs=0x7ffffffe6c60) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_lyb.c:977
977                 LOGVAL(lybs->ctx, LYE_SPEC, LY_VLOG_LYS, sparent, "Failed to find matching hash for a child of \"%s\".",
(gdb) bt
#0  lyb_parse_schema_hash (sparent=0x6082d0, mod=mod@entry=0x0, data=0x7ffff7a58045 "", data@entry=0x7ffff7a58044 "\224", yang_data_name=yang_data_name@entry=0x0, options=options@entry=8705, snode=snode@entry=0x7ffffffe6b50, lybs=0x7ffffffe6c60) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_lyb.c:977
#1  0x00007ffff7e82c82 in lyb_parse_subtree (data=0x7ffff7a58044 "\224", data@entry=0x7ffff7a58042 "\002", parent=parent@entry=0x6188f0, first_sibling=first_sibling@entry=0x0, yang_data_name=yang_data_name@entry=0x0, options=options@entry=8705, unres=unres@entry=0x60f390, lybs=0x7ffffffe6c60)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_lyb.c:1033
#2  0x00007ffff7e82e84 in lyb_parse_subtree (data=0x7ffff7a58042 "\002", data@entry=0x7ffff7a58022 " \001\030", parent=parent@entry=0x0, first_sibling=first_sibling@entry=0x7ffffffe6c58, yang_data_name=yang_data_name@entry=0x0, options=options@entry=8705, unres=unres@entry=0x60f390, lybs=0x7ffffffe6c60)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_lyb.c:1104
#3  0x00007ffff7e83156 in lyd_parse_lyb (ctx=ctx@entry=0x51a010, data=0x7ffff7a58022 " \001\030", data@entry=0x7ffff7a58000 "lyb", options=options@entry=8705, data_tree=data_tree@entry=0x0, yang_data_name=yang_data_name@entry=0x0, parsed=parsed@entry=0x0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_lyb.c:1249
#4  0x00007ffff7eb51b4 in lyd_parse_ (ctx=ctx@entry=0x51a010, rpc_act=0x0, data=data@entry=0x7ffff7a58000 "lyb", format=format@entry=LYD_LYB, options=options@entry=8705, data_tree=0x0, yang_data_name=0x0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/tree_data.c:970
#5  0x00007ffff7eb53e5 in lyd_parse_data_ (ctx=ctx@entry=0x51a010, data=0x7ffff7a58000 "lyb", format=format@entry=LYD_LYB, options=options@entry=8705, ap=ap@entry=0x7ffffffe6df0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/tree_data.c:1039
#6  0x00007ffff7eb554b in lyd_parse_fd_ (ctx=ctx@entry=0x51a010, fd=fd@entry=6, format=format@entry=LYD_LYB, options=options@entry=8705, ap=ap@entry=0x7ffffffe6df0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/tree_data.c:1074
#7  0x00007ffff7eb5698 in lyd_parse_fd (ctx=0x51a010, fd=6, format=LYD_LYB, options=8705) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/tree_data.c:1090
#8  0x00007ffff7f702c2 in sr_module_file_data_append (ly_mod=0x5f4380, ds=SR_DS_RUNNING, data=0x7ffffffe6f98) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/common.c:5109
#9  0x00007ffff7f87a1f in sr_lydmods_sched_update_data (sr_mods=0x4191b0, new_ctx=0x409670, fail=0x7ffffffe70c4) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/lyd_mods.c:1193
#10 0x00007ffff7f8a541 in sr_lydmods_sched_apply (sr_mods=0x4191b0, new_ctx=0x409670, change=0x7ffffffe70bc, fail=0x7ffffffe70c4) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/lyd_mods.c:2271
#11 0x00007ffff7f8aa87 in sr_lydmods_conn_ctx_update (main_shm=0x7ffff7a5a000, ly_ctx=0x4093f0, apply_sched=1, err_on_sched_fail=0, sr_mods=0x7ffffffe7120, changed=0x7ffffffe710c) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/lyd_mods.c:2379
#12 0x00007ffff7f56263 in sr_connect (opts=0, conn_p=0x7ffffffe71a8) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/sysrepo.c:174
#13 0x0000000000403f63 in main (argc=2, argv=0x7ffffffe7538) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/executables/sysrepoctl.c:648
(gdb) c
Continuing.
[ERR]: Failed to find matching hash for a child of "acls". (path: /ietf-access-control-list:acls)
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to connect (Operation failed)
[Inferior 1 (process 15991) exited with code 01]
```
I'm attaching the [content of my `etc/sysrepo`](https://github.com/sysrepo/sysrepo/files/6046922/etc-sysrpeo.zip) here. The update that fails our tests goes like this:
- CESNET/libyang@8a4535682effe40d8b2ba3852912cff21eec46b4 -> CESNET/libyang@6a9857533e5834e8f3a1bdf1149afa6a664334f7
- sysrepo 56eee7954c95cc455d100a74fb09c6a3815c6576 -> 15127bd35bb27781730511f2d00dd212fabfed57

**Comment by michalvasko** [comment]
I see, the problem will likely be in the previous step. I think you were somehow modifying the context, what exactly was the change?

**Comment by jktjkt** [comment]
Turns out it's easy to reproduce for me. I'm starting with a clean state:
```
[nix-shell:~/work/prog/_build/czechlight-gcc-10/velia]$ rm -rf ../target/etc-sysrepo /dev/shm/*

[nix-shell:~/work/prog/_build/czechlight-gcc-10/velia]$ sysrepoctl --list
Sysrepo repository: /home/jkt/work/prog/_build/czechlight-gcc-10/target/etc-sysrepo

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
-------------------------------------------------------------------------------------------------
ietf-datastores            | 2018-02-14 | I     | jkt:users | 664         |            |         
ietf-inet-types            | 2013-07-15 | i     |           |             |            |         
ietf-netconf               | 2011-06-01 | I     | jkt:users | 664         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | jkt:users | 664         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | jkt:users | 664         |            |         
ietf-origin                | 2018-02-14 | I     | jkt:users | 664         |            |         
ietf-yang-library          | 2019-01-04 | I     | jkt:users | 664         |            |         
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |         
ietf-yang-types            | 2013-07-15 | i     |           |             |            |         
sysrepo-monitoring         | 2021-01-15 | I     | jkt:users | 600         |            |         
sysrepo-plugind            | 2020-12-10 | I     | jkt:users | 664         |            |         
yang                       | 2017-02-20 | I     | jkt:users | 664         |            |         

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
Features: ! - Means that the feature is effectively disabled because of its false if-feature(s)
```
Then I install some modules and enable related features. This still succeeds:
```
[nix-shell:~/work/prog/_build/czechlight-gcc-10/velia]$ ctest -R sysrepo:prep:sysrepo-firewall -VV
UpdateCTestConfiguration  from :/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
Parse Config file:/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
Parse Config file:/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
Test project /home/jkt/work/prog/_build/czechlight-gcc-10/velia
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 35
    Start 35: sysrepo:prep:sysrepo-firewall

35: Test command: /home/jkt/work/cesnet/gerrit/CzechLight/velia/tests/sysrepoctl-manage-module.sh "/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl" "/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepocfg" "prepare" "YANG" "/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang" "FEATURE" "eth" "FEATURE" "match-on-eth" "FEATURE" "match-on-ipv4" "FEATURE" "ipv4" "FEATURE" "match-on-ipv6" "FEATURE" "ipv6" "FEATURE" "mixed-eth-ipv4-ipv6" "YANG" "/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang"
35: Test timeout computed to be: 1500
35: + shopt -s failglob
35: + SYSREPOCTL=/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl
35: + shift
35: + [[ ! -x /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl ]]
35: + SYSREPOCFG=/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepocfg
35: + shift
35: + [[ ! -x /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepocfg ]]
35: + MODE=prepare
35: + shift
35: + '[' prepare '!=' prepare ']'
35: + [[ 18 -gt 0 ]]
35: + [[ YANG == \Y\A\N\G ]]
35: + shift
35: + YANG_FILE=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
35: + shift
35: + [[ ! -f /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang ]]
35: ++ basename --suffix .yang /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
35: ++ sed 's/@.*//'
35: + MODULE=ietf-access-control-list
35: ++ dirname /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
35: + YANG_DIR=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --uninstall ietf-access-control-list -a
35: [ERR]: Module "ietf-access-control-list" not scheduled for installation.
35: [ERR]: Module "ietf-access-control-list" was not found in sysrepo.
35: sysrepoctl error: Failed to uninstall module "ietf-access-control-list" (Item not found)
35: + true
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --search-dirs /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang --install /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
35: + [[ 16 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=eth
35: + shift
35: + '[' -z eth ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature eth -a
35: + [[ 14 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=match-on-eth
35: + shift
35: + '[' -z match-on-eth ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature match-on-eth -a
35: + [[ 12 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=match-on-ipv4
35: + shift
35: + '[' -z match-on-ipv4 ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature match-on-ipv4 -a
35: + [[ 10 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=ipv4
35: + shift
35: + '[' -z ipv4 ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature ipv4 -a
35: + [[ 8 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=match-on-ipv6
35: + shift
35: + '[' -z match-on-ipv6 ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature match-on-ipv6 -a
35: + [[ 6 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=ipv6
35: + shift
35: + '[' -z ipv6 ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature ipv6 -a
35: + [[ 4 -gt 0 ]]
35: + [[ FEATURE != \Y\A\N\G ]]
35: + [[ FEATURE == \F\E\A\T\U\R\E ]]
35: + shift
35: + FEATURE=mixed-eth-ipv4-ipv6
35: + shift
35: + '[' -z mixed-eth-ipv4-ipv6 ']'
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --change ietf-access-control-list --enable-feature mixed-eth-ipv4-ipv6 -a
35: + [[ 2 -gt 0 ]]
35: + [[ YANG != \Y\A\N\G ]]
35: + [[ 2 -gt 0 ]]
35: + [[ YANG == \Y\A\N\G ]]
35: + shift
35: + YANG_FILE=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
35: + shift
35: + [[ ! -f /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang ]]
35: ++ basename --suffix .yang /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
35: ++ sed 's/@.*//'
35: + MODULE=czechlight-firewall
35: ++ dirname /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
35: + YANG_DIR=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang
35: + [[ prepare == \p\r\e\p\a\r\e ]]
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --uninstall czechlight-firewall -a
35: [ERR]: Module "czechlight-firewall" not scheduled for installation.
35: [ERR]: Module "czechlight-firewall" was not found in sysrepo.
35: sysrepoctl error: Failed to uninstall module "czechlight-firewall" (Item not found)
35: + true
35: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --search-dirs /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang --install /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
35: + [[ 0 -gt 0 ]]
35: + [[ 0 -gt 0 ]]
35: + [[ prepare == \u\n\i\n\s\t\a\l\l ]]
1/1 Test #35: sysrepo:prep:sysrepo-firewall ....   Passed    0.25 sec

The following tests passed:
        sysrepo:prep:sysrepo-firewall

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.25 sec
```
Now everything has been prepared:
```
[nix-shell:~/work/prog/_build/czechlight-gcc-10/velia]$ sysrepoctl --list                         
Sysrepo repository: /home/jkt/work/prog/_build/czechlight-gcc-10/target/etc-sysrepo

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features                                                                  
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
czechlight-firewall        | 2021-01-25 | I     | jkt:users | 600         |            |                                                                           
ietf-access-control-list   | 2019-03-04 | I     | jkt:users | 600         |            | eth match-on-eth match-on-ipv4 ipv4 match-on-ipv6 ipv6 mixed-eth-ipv4-ipv6
ietf-datastores            | 2018-02-14 | I     | jkt:users | 664         |            |                                                                           
ietf-ethertypes            | 2019-03-04 | i     |           |             |            |                                                                           
ietf-inet-types            | 2013-07-15 | i     |           |             |            |                                                                           
ietf-interfaces            | 2018-02-20 | I     | jkt:users | 600         |            |                                                                           
ietf-netconf               | 2011-06-01 | I     | jkt:users | 664         |            |                                                                           
ietf-netconf-notifications | 2012-02-06 | I     | jkt:users | 664         |            |                                                                           
ietf-netconf-with-defaults | 2011-06-01 | I     | jkt:users | 664         |            |                                                                           
ietf-origin                | 2018-02-14 | I     | jkt:users | 664         |            |                                                                           
ietf-packet-fields         | 2019-03-04 | i     |           |             |            |                                                                           
ietf-yang-library          | 2019-01-04 | I     | jkt:users | 664         |            |                                                                           
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |                                                                           
ietf-yang-types            | 2013-07-15 | i     |           |             |            |                                                                           
sysrepo-monitoring         | 2021-01-15 | I     | jkt:users | 600         |            |                                                                           
sysrepo-plugind            | 2020-12-10 | I     | jkt:users | 664         |            |                                                                           
yang                       | 2017-02-20 | I     | jkt:users | 664         |            |                                                                           

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
Features: ! - Means that the feature is effectively disabled because of its false if-feature(s)
```
...but when I try to go ahead and remove them, it breaks:
```
[nix-shell:~/work/prog/_build/czechlight-gcc-10/velia]$ ctest -R sysrepo:clean:sysrepo-firewall -VV
UpdateCTestConfiguration  from :/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
Parse Config file:/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
Parse Config file:/home/jkt/work/prog/_build/czechlight-gcc-10/velia/DartConfiguration.tcl
Test project /home/jkt/work/prog/_build/czechlight-gcc-10/velia
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 36
    Start 36: sysrepo:clean:sysrepo-firewall

36: Test command: /home/jkt/work/cesnet/gerrit/CzechLight/velia/tests/sysrepoctl-manage-module.sh "/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl" "/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepocfg" "uninstall" "YANG" "/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang" "FEATURE" "eth" "FEATURE" "match-on-eth" "FEATURE" "match-on-ipv4" "FEATURE" "ipv4" "FEATURE" "match-on-ipv6" "FEATURE" "ipv6" "FEATURE" "mixed-eth-ipv4-ipv6" "YANG" "/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang"
36: Test timeout computed to be: 1500
36: + shopt -s failglob
36: + SYSREPOCTL=/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl
36: + shift
36: + [[ ! -x /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl ]]
36: + SYSREPOCFG=/home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepocfg
36: + shift
36: + [[ ! -x /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepocfg ]]
36: + MODE=uninstall
36: + shift
36: + '[' uninstall '!=' prepare ']'
36: + '[' uninstall '!=' uninstall ']'
36: + [[ 18 -gt 0 ]]
36: + [[ YANG == \Y\A\N\G ]]
36: + shift
36: + YANG_FILE=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
36: + shift
36: + [[ ! -f /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang ]]
36: ++ basename --suffix .yang /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
36: ++ sed 's/@.*//'
36: + MODULE=ietf-access-control-list
36: ++ dirname /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/ietf-access-control-list@2019-03-04.yang
36: + YANG_DIR=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ uninstall == \u\n\i\n\s\t\a\l\l ]]
36: + MODULE_LIST=("${MODULE}" "${MODULE_LIST[@]}")
36: + [[ 16 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=eth
36: + shift
36: + '[' -z eth ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 14 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=match-on-eth
36: + shift
36: + '[' -z match-on-eth ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 12 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=match-on-ipv4
36: + shift
36: + '[' -z match-on-ipv4 ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 10 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=ipv4
36: + shift
36: + '[' -z ipv4 ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 8 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=match-on-ipv6
36: + shift
36: + '[' -z match-on-ipv6 ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 6 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=ipv6
36: + shift
36: + '[' -z ipv6 ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 4 -gt 0 ]]
36: + [[ FEATURE != \Y\A\N\G ]]
36: + [[ FEATURE == \F\E\A\T\U\R\E ]]
36: + shift
36: + FEATURE=mixed-eth-ipv4-ipv6
36: + shift
36: + '[' -z mixed-eth-ipv4-ipv6 ']'
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ 2 -gt 0 ]]
36: + [[ YANG != \Y\A\N\G ]]
36: + [[ 2 -gt 0 ]]
36: + [[ YANG == \Y\A\N\G ]]
36: + shift
36: + YANG_FILE=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
36: + shift
36: + [[ ! -f /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang ]]
36: ++ basename --suffix .yang /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
36: ++ sed 's/@.*//'
36: + MODULE=czechlight-firewall
36: ++ dirname /home/jkt/work/cesnet/gerrit/CzechLight/velia/yang/czechlight-firewall@2021-01-25.yang
36: + YANG_DIR=/home/jkt/work/cesnet/gerrit/CzechLight/velia/yang
36: + [[ uninstall == \p\r\e\p\a\r\e ]]
36: + [[ uninstall == \u\n\i\n\s\t\a\l\l ]]
36: + MODULE_LIST=("${MODULE}" "${MODULE_LIST[@]}")
36: + [[ 0 -gt 0 ]]
36: + [[ 0 -gt 0 ]]
36: + [[ uninstall == \u\n\i\n\s\t\a\l\l ]]
36: + for module in "${MODULE_LIST[@]}"
36: + /home/jkt/work/prog/_build/czechlight-gcc-10/target/bin/sysrepoctl --uninstall czechlight-firewall -a
36: [ERR]: Failed to find matching hash for a child of "acls". (path: /ietf-access-control-list:acls)
36: [ERR]: Failed to update data for the new context.
36: sysrepoctl error: Failed to apply changes (Operation failed)
1/1 Test #36: sysrepo:clean:sysrepo-firewall ...***Failed    0.04 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.04 sec

The following tests FAILED:
         36 - sysrepo:clean:sysrepo-firewall (Failed)
Errors while running CTest
```
You can [find all the YANG modules here](https://github.com/CESNET/velia/tree/master/yang).

**Comment by michalvasko** [comment]
Right, I had to revert the whole feature for now because it turned out to be much more complex than I thought so we will continue working on it and commit it only once we are reasonably sure it works correctly and has some specific test cases. So, it should work fine again now.
