### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by immibis** [sysrepo/sysrepo#238]
<pre>
mp@t460s:~/ietf962/sysrepo-plugin-system$ sudo gdb --args sysrepod -dl4
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sysrepod...done.
(gdb) run
Starting program: /usr/bin/sysrepod -dl4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[DBG] (sr_log_stderr:146) Setting log level for stderr logs to 4.
[DBG] (main:117) Sysrepo daemon initialization started.
[DBG] (cm_init:1668) Connection Manager init started.
[DBG] (sr_cbuff_init:402) Initiating circular buffer for 10 elements.
[DBG] (sm_init:287) Session Manager initialized successfully, ctx=0x604230.
[DBG] (cm_server_init:154) Initializing sysrepo server at socket=/var/run/sysrepod.sock
[DBG] (rp_init:1906) Request Processor init started.
[DBG] (sr_cbuff_init:402) Initiating circular buffer for 10 elements.
[DBG] (np_init:338) Notification Processor initialized successfully.
[INF] (dm_init:1067) Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[DBG] (sr_locking_set_lock_fd:734) File /etc/sysrepo/data/turing-machine.persist has been locked
[DBG] (pm_load_data_tree:173) Persist data successfully loaded from file '/etc/sysrepo/data/turing-machine.persist'.
[DBG] (sr_locking_set_unlock_close_fd:803) File /etc/sysrepo/data/turing-machine.persist (fd = 6) has been unlocked
[DBG] (pm_get_module_info:579) Returning info from 'turing-machine' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[INF] (dm_load_all_schemas:449) Schema file for module 'turing-machine@2013-12-27' loaded successfully
[DBG] (pm_load_data_tree:138) Persist data file '/etc/sysrepo/data/iana-if-type.persist' does not exist.
[WRN] (pm_load_data_tree:159) Persist data tree load for 'iana-if-type' has failed.
[INF] (dm_load_all_schemas:449) Schema file for module 'iana-if-type@2014-05-08' loaded successfully
[DBG] (sr_locking_set_lock_fd:734) File /etc/sysrepo/data/ietf-interfaces.persist has been locked
[DBG] (pm_load_data_tree:173) Persist data successfully loaded from file '/etc/sysrepo/data/ietf-interfaces.persist'.
[DBG] (sr_locking_set_unlock_close_fd:803) File /etc/sysrepo/data/ietf-interfaces.persist (fd = 6) has been unlocked
[INF] (dm_load_all_schemas:449) Schema file for module 'ietf-interfaces@2014-05-08' loaded successfully
[DBG] (pm_load_data_tree:138) Persist data file '/etc/sysrepo/data/ietf-ip.persist' does not exist.
[WRN] (pm_load_data_tree:159) Persist data tree load for 'ietf-ip' has failed.
[INF] (dm_load_all_schemas:449) Schema file for module 'ietf-ip@2014-06-16' loaded successfully
[DBG] (sr_locking_set_lock_fd:734) File /etc/sysrepo/data/sysrepo-raspberry-demo.persist has been locked
[DBG] (pm_load_data_tree:173) Persist data successfully loaded from file '/etc/sysrepo/data/sysrepo-raspberry-demo.persist'.
[DBG] (sr_locking_set_unlock_close_fd:803) File /etc/sysrepo/data/sysrepo-raspberry-demo.persist (fd = 6) has been unlocked
[INF] (dm_load_all_schemas:449) Schema file for module 'sysrepo-raspberry-demo@2016-07-12' loaded successfully
[DBG] (sr_locking_set_lock_fd:734) File /etc/sysrepo/data/ietf-netconf-acm.persist has been locked
[DBG] (pm_load_data_tree:173) Persist data successfully loaded from file '/etc/sysrepo/data/ietf-netconf-acm.persist'.
[DBG] (sr_locking_set_unlock_close_fd:803) File /etc/sysrepo/data/ietf-netconf-acm.persist (fd = 6) has been unlocked
[INF] (dm_load_all_schemas:449) Schema file for module 'ietf-netconf-acm@2012-02-22' loaded successfully
[DBG] (pm_load_data_tree:138) Persist data file '/etc/sysrepo/data/iana-crypt-hash.persist' does not exist.
[WRN] (pm_load_data_tree:159) Persist data tree load for 'iana-crypt-hash' has failed.
[INF] (dm_load_all_schemas:449) Schema file for module 'iana-crypt-hash@2014-04-04' loaded successfully
[DBG] (dm_ly_log_cb:689) libyang error: Opening file "/etc/sysrepo/yang/ietf-system@2014-08-06.yang" failed (No such file or directory).
[WRN] (dm_load_schema_file:312) Unable to parse a schema file: /etc/sysrepo/yang/ietf-system@2014-08-06.yang
[ERR] (dm_load_all_schemas:445) Loading schema file for module 'ietf-system@2014-08-06' failed.
[ERR] (rp_init:1957) Data Manager initialization failed.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff72f59f0 in rb_openlist () from /usr/local/lib/libredblack.so.0
(gdb) bt
#0  0x00007ffff72f59f0 in rb_openlist () from /usr/local/lib/libredblack.so.0
#1  0x00007ffff72f4b77 in rbopenlist () from /usr/local/lib/libredblack.so.0
#2  0x00007ffff7b06cb7 in sr_btree_cleanup (tree=0x623d90) at /home/mp/ietf962/sysrepo/src/common/sr_data_structs.c:271
#3  0x00007ffff7b67f91 in dm_cleanup (dm_ctx=0x61b250) at /home/mp/ietf962/sysrepo/src/data_manager.c:1147
#4  0x00007ffff7b44c11 in rp_init (cm_ctx=0x604030, rp_ctx_p=0x604040) at /home/mp/ietf962/sysrepo/src/request_processor.c:1981
#5  0x00007ffff7b2c630 in cm_init (mode=CM_MODE_DAEMON, socket_path=0x401ae1 "/var/run/sysrepod.sock", cm_ctx_p=0x7fffffffe9f8) at /home/mp/ietf962/sysrepo/src/connection_manager.c:1721
#6  0x0000000000401251 in main (argc=2, argv=0x7fffffffeae8) at /home/mp/ietf962/sysrepo/src/executables/sysrepod.c:120
(gdb) frame 4
#4  0x00007ffff7b44c11 in rp_init (cm_ctx=0x604030, rp_ctx_p=0x604040) at /home/mp/ietf962/sysrepo/src/request_processor.c:1981
1981	    dm_cleanup(ctx->dm_ctx);
(gdb) list
1976	
1977	    *rp_ctx_p = ctx;
1978	    return SR_ERR_OK;
1979	
1980	cleanup:
1981	    dm_cleanup(ctx->dm_ctx);
1982	    np_cleanup(ctx->np_ctx);
1983	    pm_cleanup(ctx->pm_ctx);
1984	    ac_cleanup(ctx->ac_ctx);
1985	    sr_cbuff_cleanup(ctx->request_queue);
</pre>

Installed modules are:
* iana-crypt-hash
* ietf-interfaces
* ietf-netconf-acm
* sysrepo-raspberry-demo
* iana-if-type
* ietf-ip
* turing-machine

Also, ietf-system was installed, then uninstalled, then I tried to install it again (which gave me an "internal error" message) then I restarted sysrepod and got this crash.

[core.zip](https://github.com/sysrepo/sysrepo/files/367248/core.zip)

**Comment by rastislavszabo** [comment]
Fixed in the devel branch, shouldn't be an issue in master.
