### ISSUE TITLE
Setting state data on a list leaf using python bidings

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2381]
I am using the python bindings ([based off this example](https://github.com/sysrepo/sysrepo/blob/v1.4.104/bindings/python/examples/python_oper_get_data_example.py#L35)) to create a callback that handles getting state data. My yang file looks like this:

```.yang
    container MYMOD-STATE {
      config false;
      // for each ruleID, know how much data is flowing.

      container PacketOperationConf {
        config false;
        list RuleID {
          key id;
          leaf id {
            config false;
            type uint32;
          }
          leaf byte_count {
            config false;
            type uint32;
          }
          leaf duration {
            config false;
            type uint32;
          }
        }
      }
    }
```

I am able to set the `id` field however the `byte_count` and `duration` causes errors.

```.py
def mymod_state_cb(sess, module_name, path, request_xpath, request_id, parent, private_data):
    try:
        ctx = sess.get_context()
        mod = ctx.get_module(module_name)

        parent.reset(sr.Data_Node(ctx, "/mymod-full:MYMOD-STATE", None, sr.LYD_ANYDATA_CONSTSTRING, 0))
        packetOperationConf = sr.Data_Node(parent, mod, "PacketOperationConf")
        rule_id = sr.Data_Node(packetOperationConf, mod, "RuleID")
        rule_id_a = sr.Data_Node(rule_id, mod, "id", "12345")
        #### Uncommenting below causes errors ####
        #bc = sr.Data_Node(rule_id_a, mod, "byte_count", "11111")
        #d = sr.Data_Node(rule_id_a, mod, "duration", "22222")
    except Exception:
        logging.error(traceback.format_exc())

    return sr.SR_ERR_OK
```

With the lines `#bc` and `#d` commented out, after running this code, I get this back from my `<get>`:
```.xml
> get --filter-xpath=/mymod-full:MYMOD-STATE --rpc-timeout=1
DATA
<MYMOD-STATE xmlns="urn:com:tug:mymod-full">
  <PacketOperationConf>
    <RuleID>
      <id>12345</id>
    </RuleID>
  </PacketOperationConf>
</MYMOD-STATE>
```

When I uncomment those lines, I see this error in python:
```
libyang[0]: Invalid arguments (lyd_new_leaf()).
2021-03-29T18:09:57,142 ERROR    [sysrepo_rmbn_websocket_server.py:117] Traceback (most recent call last):
  File "my_script.py", line 110, in mymod_state_cb
    bc = sr.Data_Node(rule_id_a, mod, "byte_count", "11111")
  File "/usr/lib64/python3.6/site-packages/sysrepo.py", line 3806, in __init__
    this = _sysrepo.new_Data_Node(*args)
RuntimeError: libyang error
```

So it seems that setting the value of a leaf that exists within a list is not as trivial as `sr.Data_Node(direct_parent_node, mod, "byte_count", "11111")` but after a fair amount of googling and searching other issues here, I can't find how to make these value edits happen.

**Comment by esend7881** [comment]
I believe I got this working. I made some changes to the yang model and python code:

```.yang
    container MYMOD-STATE {
      config false;
      container PacketOperationConf {
        config false;
        list RuleID {
          key id;
          leaf id {
            type uint32;
          }
          leaf byte_count {
            type uint32;
          }
          leaf duration {
            type uint32;
          }
        }
      }
    }
```

```.py
def mymod_state_cb(sess, module_name, path, request_xpath, request_id, parent, private_data):
    try:
        ctx = sess.get_context()
        mod = ctx.get_module(module_name)
        parent.reset(sr.Data_Node(ctx, "/mymod-full:MYMOD-STATE", None, sr.LYD_ANYDATA_CONSTSTRING, 0))
        packetOperationConf = sr.Data_Node(parent, mod, "PacketOperationConf")
        rule_id_a = sr.Data_Node(packetOperationConf, mod, "RuleID")
        id_a = sr.Data_Node(rule_id_a, mod, "id", "1")
        bc_a = sr.Data_Node(rule_id_a, mod, "byte_count", "2")
        d_a = sr.Data_Node(rule_id_a, mod, "duration", "3")
        rule_id_b = sr.Data_Node(packetOperationConf, mod, "RuleID")
        id_b = sr.Data_Node(rule_id_b, mod, "id", "4")
        bc_b = sr.Data_Node(rule_id_b, mod, "byte_count", "5")
        d_b = sr.Data_Node(rule_id_b, mod, "duration", "6")
        logging.info("\npacketOperationConf: '%s'\nrule_id_a: '%s'\nrule_id_a: '%s'\nbc_a: '%s'\nd_a: '%s'",
                     packetOperationConf, rule_id_a, id_a,
                     bc_a, d_a)
        logging.info("---END---")
    except Exception:
        logging.error(traceback.format_exc())

    return sr.SR_ERR_OK
```

Creates:
```.xml
> get --filter-xpath=/mymod-full:*            
DATA                                         
<MYMOD-STATE xmlns="urn:com:tug:mymod-full">   
  <PacketOperationConf>                      
    <RuleID>                                 
      <id>1</id>                             
      <byte_count>2</byte_count>             
      <duration>3</duration>                 
    </RuleID>                                
    <RuleID>                                 
      <id>4</id>                             
      <byte_count>5</byte_count>             
      <duration>6</duration>                 
    </RuleID>                                
  </PacketOperationConf>                     
</MYMOD-STATE>                                
```

So yeah, I guess I just needed to keep cleaning things up. I'll close this for now, but as I flesh this out, I may re-open if I find this "fix" was a fluke.
