### ISSUE TITLE
ly2: Segmentation fault when importing NACM rule

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2407]
Hi,

I encounter segmentation fault when I try to import NACM rule from JSON file:

```
$ sysrepoctl -i yang/ietf-netconf-acm@2018-02-14.yang
$ sysrepoctl -i yang/ietf-netconf-monitoring@2010-10-04.yang
$ sysrepocfg --edit=ietf-netconf-monitoring.json --datastore=startup --format=json --module ietf-netconf-acm

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff785694a in lyd_dup_r (node=0x555555777280, parent=0x0, first=0x7fffffffd048, options=2, dup_p=0x7fffffffd048) at /opt/dev/libyang/src/tree_data.c:3222
3222	/opt/dev/libyang/src/tree_data.c: No such file or directory.
(gdb) bt
#0  0x00007ffff785694a in lyd_dup_r (node=0x555555777280, parent=0x0, first=0x7fffffffd048, options=2, dup_p=0x7fffffffd048) at /opt/dev/libyang/src/tree_data.c:3222
#1  0x00007ffff7857034 in lyd_dup (node=0x555555777280, parent=0x0, options=2, nosiblings=1 '\001', dup=0x7fffffffd1a0) at /opt/dev/libyang/src/tree_data.c:3352
#2  0x00007ffff78570ec in lyd_dup_single (node=0x555555777280, parent=0x0, options=2, dup=0x7fffffffd1a0) at /opt/dev/libyang/src/tree_data.c:3377
#3  0x00007ffff7b89197 in sr_edit_apply_create (first_node=0x555555777608, parent_node=0x5555557775d0, match_node=0x7fffffffd1a0, edit_node=0x555555777280, diff_parent=0x5555557e3da0, diff_root=0x7fffffffd470, 
    diff_node=0x7fffffffd1b0, next_op=0x7fffffffd188, change=0x7fffffffd4cc) at /opt/dev/sysrepo/src/edit_diff.c:1704
#4  0x00007ffff7b896f8 in sr_edit_apply_r (first_node=0x555555777608, parent_node=0x5555557775d0, edit_node=0x555555777280, parent_op=EDIT_MERGE, diff_parent=0x5555557e3da0, diff_root=0x7fffffffd470, flags=0, 
    change=0x7fffffffd4cc) at /opt/dev/sysrepo/src/edit_diff.c:1851
#5  0x00007ffff7b89ba0 in sr_edit_apply_r (first_node=0x55555577b228, parent_node=0x55555577b1f0, edit_node=0x5555557e9790, parent_op=EDIT_MERGE, diff_parent=0x5555557e3da0, diff_root=0x7fffffffd470, flags=0, 
    change=0x7fffffffd4cc) at /opt/dev/sysrepo/src/edit_diff.c:1961
#6  0x00007ffff7b89ba0 in sr_edit_apply_r (first_node=0x5555557b13e8, parent_node=0x5555557b13b0, edit_node=0x5555557ea6b0, parent_op=EDIT_MERGE, diff_parent=0x55555577b870, diff_root=0x7fffffffd470, flags=0, 
    change=0x7fffffffd4cc) at /opt/dev/sysrepo/src/edit_diff.c:1961
#7  0x00007ffff7b89ba0 in sr_edit_apply_r (first_node=0x7fffffffd560, parent_node=0x0, edit_node=0x5555557d25f0, parent_op=EDIT_CONTINUE, diff_parent=0x5555557f0750, diff_root=0x7fffffffd470, flags=0, 
    change=0x7fffffffd4cc) at /opt/dev/sysrepo/src/edit_diff.c:1961
#8  0x00007ffff7b89d55 in sr_edit_mod_apply (edit=0x5555557d25f0, ly_mod=0x5555557c3630, data=0x7fffffffd560, diff=0x7fffffffd558, change=0x7fffffffd4cc) at /opt/dev/sysrepo/src/edit_diff.c:2007
#9  0x00007ffff7b7e4d6 in sr_modinfo_edit_apply (mod_info=0x7fffffffd550, edit=0x5555557d25f0, create_diff=1) at /opt/dev/sysrepo/src/modinfo.c:156
#10 0x00007ffff7b657f5 in sr_apply_changes (session=0x555555796ed0, timeout_ms=5000) at /opt/dev/sysrepo/src/sysrepo.c:2277
#11 0x0000555555556a60 in op_edit (sess=0x555555796ed0, file_path=0x7fffffffde51 "nacm/ietf-netconf-monitoring.json", editor=0x0, 
    module_name=0x7fffffffdec9 "ietf-netconf-acm", format=LYD_JSON, lock=0, not_strict=0, wd_opt=0, timeout_s=0) at /opt/dev/sysrepo/src/executables/sysrepocfg.c:419
#12 0x0000555555557c5a in main (argc=6, argv=0x7fffffffda28) at /opt/dev/sysrepo/src/executables/sysrepocfg.c:906
```

The content of ietf-netconf-monitoring.json:

```
{
  "ietf-netconf-acm:nacm": {
    "rule-list": [
      {
        "name": "test1",
        "group": ["test-group"],
        "rule": [
          {
            "name": "test-rule-deny",
            "module-name": "ietf-netconf-monitoring",
            "path": "/ietf-netconf-monitoring:netconf-state/sessions",
            "action": "deny"
          }
        ]
      }
    ]
  }
}
```

libyang version: 698275050fb5b06a7491f5efd6c811fddfd5e681
sysrepo version: 5e1b9fcbbc8f0df00fb6963f4d14952c6f19d5b0

Thanks!

**Comment by michalvasko** [comment]
Should be fixed in the latest *libyang*.

**Comment by awesomenode** [comment]
The segfault is gone. Thanks!
