### ISSUE TITLE
Segmentation fault while loading BBF yang modules

### ISSUE THREAD

**Issue by andre-brizido** [sysrepo/sysrepo#2472]
Hi

sysrepo fails to load several BBf yang modules. In attach a zip [bbf-yangs.zip](https://github.com/sysrepo/sysrepo/files/6638817/bbf-yangs.zip) with yangs and the script used for installing them.
Below are some error examples while running the _install_modules_v1.x.sh:
```
+ sysrepoctl -s . --install bbf-fast.yang
Segmentation fault (core dumped)
+ sysrepoctl -s . --install bbf-melt.yang
sysrepoctl: /mnt/Projects/netconf/netopeer2-tests/src/libyang/src/schema_compile.c:470: lys_compile_identities_derived: Assertion `v < LY_ARRAY_COUNT(idents_p)' failed.
+ sysrepoctl -s . --install bbf-qos-shaping.yang
[ERR]: Augment target node "/if:interfaces/if:interface/bbf-qos-tm:tm-root/bbf-qos-tm:children-type/bbf-qos-tm:queues/bbf-qos-tm:queue" from module "bbf-qos-shaping" was not found.
[ERR]: Augment target node "/if:interfaces/if:interface/bbf-qos-tm:tm-root" from module "bbf-qos-shaping" was not found.
sysrepoctl error: Failed to install module "bbf-qos-shaping.yang" (libyang error)
For more details you may try to increase the verbosity up to "-v3".
```

Stack strace for one SEG fault:
```
Program received signal SIGSEGV, Segmentation fault.
_IO_vfprintf_internal (s=s@entry=0x7fffff7ff580, format=format@entry=0x7ffff7bac5a0 "%s/yang/%s%s%s.yang", ap=ap@entry=0x7fffff7ff6b0) at vfprintf.c:1320
1320    vfprintf.c: No such file or directory.
(gdb) bt
#0  _IO_vfprintf_internal (s=s@entry=0x7fffff7ff580, format=format@entry=0x7ffff7bac5a0 "%s/yang/%s%s%s.yang", ap=ap@entry=0x7fffff7ff6b0) at vfprintf.c:1320
#1  0x00007ffff74b4672 in _IO_vasprintf (result_ptr=0x7fffff7ff820, format=0x7ffff7bac5a0 "%s/yang/%s%s%s.yang", args=args@entry=0x7fffff7ff6b0) at vasprintf.c:59
#2  0x00007ffff7491244 in ___asprintf (string_ptr=<optimized out>, format=<optimized out>) at asprintf.c:35
#3  0x00007ffff7b71e15 in sr_path_yang_file (mod_name=0x555555954190 "ietf-interfaces", mod_rev=0x5555558f9be0 "2018-02-20", path=0x7fffff7ff820)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:2088
#4  0x00007ffff7b70721 in sr_store_module_file (ly_mod=0x5555559432f0, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1559
#5  0x00007ffff7b70a9a in sr_store_module_files (ly_mod=0x5555559432f0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1654
#6  0x00007ffff7b71249 in sr_create_module_imps_incs_r (ly_mod=0x5555558f1de0, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1819
#7  0x00007ffff7b7127f in sr_create_module_imps_incs_r (ly_mod=0x555555944240, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1823
#8  0x00007ffff7b7127f in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x555555908c10)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1823
#9  0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#10 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#11 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#12 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#13 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#14 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#15 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#16 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#17 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#18 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#19 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#20 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#21 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#22 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#23 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#24 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#25 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x0) at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835
#26 0x00007ffff7b71354 in sr_create_module_imps_incs_r (ly_mod=0x5555558b9090, lysp_submod=0x5555559074b0)
    at /mnt/Projects/netconf/netopeer2-tests/src/sysrepo/src/common.c:1835

(...)
```

It seems that the function sr_create_module_imps_incs_r entered a recursive loop because at a given point ly_mod, includes[u].submodule is null.
Adding the check:
```        
       if (includes[u].submodule) {
              if ((err_info = sr_create_module_imps_incs_r(ly_mod, includes[u].submodule))) {
                  return err_info;
              }
        }
```
seems to solve at least some Segmentation faults, but the fact of being null may just be a symptom that something was already wrong because the LY_ARRAY_COUNT Assertion still happens and netopeer2 eventually fails with:

```
[INF]: NP: Generated new event (netconf-session-start).
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

Best regards
Andre

**Comment by michalvasko** [comment]
Okay, the first problem should be fixed in *sysrepo*, the second one in *libyang*, and the third one in a PR https://github.com/CESNET/libyang/pull/1623 I have created sooner today, seems to have "accidentally" fixed it. Should be merged tomorrow.

**Comment by andre-brizido** [comment]
I confirm, the modules are loaded correctly into sysrepo.
