### ISSUE TITLE
sysrepocfg crashes during config change 

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2538]
Hi, 

sysrepocfg crashes  with below sample yang and xml

```
[root@pwredg85021 ]# yanglint --version
yanglint 2.0.71
[root@pwredg85021 ]# netopeer2-server -V
netopeer2-server 2.0.15
compile time: Aug 13 2021, 01:18:12
[root@pwredg85021 ]# sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.29 (SO v6.2.2)

```
[root@pwredg85021 cuduyang]# 

#### o-ran-heartbeat-management.yang
```
module o-ran-heartbeat-management {
  yang-version 1.1;
  namespace "urn:o-ran:heartbeat-management:1.0";
  prefix o-ran-hbeat;

  revision 2020-06-30 {
  }

  container heartbeat {
    leaf heartbeatPeriod {
      type uint8 {
        range "0 | 5..60";
      }
      units "minutes";
      default "5";
    }
    leaf countDownTimer {
      type uint8 {
        range "0..60";
      }
      units "minutes";
    }
  }
}

```
#### cdtdel.xml
```
<heartbeat  xmlns="urn:o-ran:heartbeat-management:1.0"
                xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
     <countDownTimer xc:operation="delete"> </countDownTimer>
</heartbeat>
```
1. install yang
` sysrepoctl -i o-ran-heartbeat-management.yang ` 
2. apply config xml.
` sysrepocfg -I=/tmp/cdtdel.xml -d running `

##### below is the backtrace.
```
(gdb) bt
#0  0x00007f998a2e38a4 in lyd_parse.constprop.12 () from /usr/local/lib64/libyang.so.2
#1  0x00007f998a2e3b39 in lyd_parse_data () from /usr/local/lib64/libyang.so.2
#2  0x0000000000402222 in step_load_data (sess=0x1776cb0, file_path=0x7fff878bc5c2 "=/tmp/cdtdel.xml", format=LYD_XML, data_type=DATA_CONFIG, not_strict=0, opaq=0, 
    data=0x7fff878bbc80) at /home/gy1005/sysrepo/src/executables/sysrepocfg.c:260
#3  0x000000000040247f in op_import (sess=0x1776cb0, file_path=0x7fff878bc5c2 "=/tmp/cdtdel.xml", module_name=0x0, format=LYD_UNKNOWN, not_strict=0, timeout_s=0)
    at /home/gy1005/sysrepo/src/executables/sysrepocfg.c:329
#4  0x000000000040383c in main (argc=4, argv=0x7fff878bc0b8) at /home/gy1005/sysrepo/src/executables/sysrepocfg.c:907
(gdb) 

```

#### Netopeer Crash
netopeer-server crash is also seen with below backtrace, 
Steps:
1. install same yang 
2. run netopeer2-server and cli
3. edit-config with above xml.
4. netopeer2-server crashes.
```
(gdb) bt
#0  0x00007ff3147336be in sr_edit_apply_delete (match_node=0x0, val_equal=0, edit_node=0x7ff2fc001630, next_op=0x7ff30f421730)
    at /home/gy1005/sysrepo/src/edit_diff.c:2258
#1  0x00007ff314733a52 in sr_edit_apply_r (first_node=0x7ff2fc0017c8, parent_node=0x7ff2fc001790, edit_node=0x7ff2fc001630, parent_op=EDIT_MERGE, diff_parent=0x7ff2fc0018f0, 
    diff_root=0x7ff30f421898, oper_edit=0, flags=0, change=0x7ff30f421904) at /home/gy1005/sysrepo/src/edit_diff.c:2355
#2  0x00007ff314733eba in sr_edit_apply_r (first_node=0x7ff30f421970, parent_node=0x0, edit_node=0x7ff2fc0015e0, parent_op=EDIT_CONTINUE, diff_parent=0x7ff2fc0018f0, 
    diff_root=0x7ff30f421898, oper_edit=0, flags=0, change=0x7ff30f421904) at /home/gy1005/sysrepo/src/edit_diff.c:2452
#3  0x00007ff314734058 in sr_edit_mod_apply (edit=0x7ff2fc0015e0, ly_mod=0xf49dc0, oper_edit=0, data=0x7ff30f421970, diff=0x7ff30f421968, change=0x7ff30f421904)
    at /home/gy1005/sysrepo/src/edit_diff.c:2497
#4  0x00007ff314727d8e in sr_modinfo_edit_apply (mod_info=0x7ff30f421960, edit=0x7ff2fc0015e0, create_diff=1)
    at /home/gy1005/sysrepo/src/modinfo.c:187
#5  0x00007ff314710033 in sr_apply_changes (session=0x7ff2f8006670, timeout_ms=5000)
    at /home/gy1005/sysrepo/src/sysrepo.c:2551
#6  0x0000000000410375 in np2srv_rpc_editconfig_cb (session=0x7ff2fc000d60, UNUSED_sub_id=2, UNUSED_op_path=0xfd8eb0 "/ietf-netconf:edit-config", input=0x7ff2fc000b40, event=SR_EV_RPC, 
    UNUSED_request_id=2, UNUSED_output=0x7ff2fc000ca0, UNUSED_private_data=0x0) at /home/gy1005/netopeer2/src/netconf.c:412
#7  0x00007ff31474e4bd in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x10716c0, ev_sess=0x7ff2fc000d60, input_op=0x7ff2fc000b40, event=SR_SUB_EV_RPC, request_id=2, 
    output_op=0x7ff30f421ba0, err_code=0x7ff30f421b94) at /home/gy1005/sysrepo/src/shm_sub.c:2897
#8  0x00007ff31474f137 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x100d0e0, conn=0xe600f0)
    at /home/gy1005/sysrepo/src/shm_sub.c:3182
#9  0x00007ff31471177f in sr_process_events (subscription=0x1078f70, session=0x0, stop_time_in=0x7ff30f421cb8)
    at /home/gy1005/sysrepo/src/sysrepo.c:3130
#10 0x00007ff31474ffbf in sr_shmsub_listen_thread (arg=0x1078f70) at /home/gy1005/sysrepo/src/shm_sub.c:3578
#11 0x00007ff314c6de65 in start_thread () from /usr/lib64/libpthread.so.0
#12 0x00007ff31443388d in clone () from /usr/lib64/libc.so.6
```

(gdb) f 0
#0  0x00007ff3147336be in sr_edit_apply_delete (match_node=0x0, val_equal=0, edit_node=0x7ff2fc001630, next_op=0x7ff30f421730)
    at /home/gy1005/sysrepo/src/edit_diff.c:2258
2258	in /home/gy1005/sysrepo/src/edit_diff.c
(gdb) p *edit_node 
$1 = {hash = 0, flags = 4, **schema = 0x0,** parent = 0x7ff2fc0015e0, next = 0x0, prev = 0x7ff2fc001630, meta = 0x0, priv = 0x0}

Its crashing due to `edit_node->schema` is `NULL`

Thanks
Govind.

**Comment by michalvasko** [comment]
Right, please try the latest *sysrepo*, it has probably been fixed recently.
