### ISSUE TITLE
sr_get_items() failure with debug version

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2592]
Hi!

When trying to list some items from the running datastore with union get using `sr_get_items()` I got the following error:
```
./get_items "/ietf-hardware:hardware//. | /ietf-interfaces:interfaces/interface//."
Application will get "/ietf-hardware:hardware//. | /ietf-interfaces:interfaces/interface//." from "running" datastore.

get_items: ./libyang/src/xpath.c:1697: set_sort: Assertion `!lyht_find(set->ht, &hnode, hash, NULL)' failed.
Aborted (core dumped)
```

Backtrace from coredump:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f5cde682921 in __GI_abort () at abort.c:79
#2  0x00007f5cde67248a in __assert_fail_base (fmt=0x7f5cde7f9750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f5cde213478 "!lyht_find(set->ht, &hnode, hash, NULL)", 
    file=file@entry=0x7f5cde212ef8 "./libyang/src/xpath.c", line=line@entry=1697, function=function@entry=0x7f5cde214d08 <__PRETTY_FUNCTION__.13751> "set_sort") at assert.c:92
#3  0x00007f5cde672502 in __GI___assert_fail (assertion=0x7f5cde213478 "!lyht_find(set->ht, &hnode, hash, NULL)", file=0x7f5cde212ef8 "./libyang/src/xpath.c", line=1697, 
    function=0x7f5cde214d08 <__PRETTY_FUNCTION__.13751> "set_sort") at assert.c:101
#4  0x00007f5cde1d6a26 in set_sort (set=0x7ffe0aafd0a0) at ./libyang/src/xpath.c:1697
#5  0x00007f5cde1e2bc2 in moveto_union (set1=0x7ffe0aafd0a0, set2=0x7ffe0aafcf00) at ./libyang/src/xpath.c:6074
#6  0x00007f5cde1e8665 in eval_union_expr (exp=0x56264eafd710, tok_idx=0x7ffe0aafd032, repeat=1, set=0x7ffe0aafd0a0, options=1) at ./libyang/src/xpath.c:7953
#7  0x00007f5cde1ea43f in eval_expr_select (exp=0x56264eafd710, tok_idx=0x7ffe0aafd032, etype=LYXP_EXPR_NONE, set=0x7ffe0aafd0a0, options=1) at ./libyang/src/xpath.c:8487
#8  0x00007f5cde1ea8a1 in lyxp_eval (ctx=0x56264e9c9ab0, exp=0x56264eafd710, cur_mod=0x0, format=LY_VALUE_JSON, prefix_data=0x0, ctx_node=0x56264e9e8bf0, tree=0x56264e9e8bf0, set=0x7ffe0aafd0a0, 
    options=1) at ./libyang/src/xpath.c:8581
#9  0x00007f5cde129d81 in lyd_find_xpath (ctx_node=0x56264e9e8bf0, xpath=0x7ffe0aafe256 "/ietf-hardware:hardware//. | /ietf-interfaces:interfaces/interface//.", set=0x7ffe0aafd1f8)
    at ./libyang/src/tree_data.c:4428
#10 0x00007f5cdea5ff5c in sr_modinfo_get_filter (mod_info=0x7ffe0aafd210, xpath=0x7ffe0aafe256 "/ietf-hardware:hardware//. | /ietf-interfaces:interfaces/interface//.", session=0x56264e9f5e00, 
    result=0x7ffe0aafd1f8) at ./sysrepo/src/modinfo.c:2201
#11 0x00007f5cdea3e3de in sr_get_items (session=0x56264e9f5e00, xpath=0x7ffe0aafe256 "/ietf-hardware:hardware//. | /ietf-interfaces:interfaces/interface//.", timeout_ms=5000, opts=0, 
    values=0x7ffe0aafd290, value_cnt=0x7ffe0aafd298) at ./sysrepo/src/sysrepo.c:1738
#12 0x000056264d33af50 in main (argc=2, argv=0x7ffe0aafd3a8) at sr_get_items_example.c:164
```

I've attached the code (though it's basically the sr_get_items_example.c from sysrepo) and the example config, but should be easy to reproduce.
[get_items_issue.tar.gz](https://github.com/sysrepo/sysrepo/files/7260513/get_items_issue.tar.gz)

I've used the latest devel libyang and sysrepo.
The error only occurs with the debug versions.

Thanks!

**Comment by michalvasko** [comment]
An oversight in *libyang*, should be fixed now.

**Comment by awesomenode** [comment]
Thanks, it works fine now!
