### ISSUE TITLE
Segmentation fault in sr_get_item after delete from operational

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2725]
Hi,

I ran into segmentation fault in `sr_get_item()` after deleting list item from pushed operational data.
I attached a simple application for reproduction.
[reprod.zip](https://github.com/sysrepo/sysrepo/files/8047386/reprod.zip)

```
$ gdb ./main 
...
(gdb) r
Starting program: main 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff56ce700 (LWP 380)]

Thread 1 "main" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b82bdb in sr_edit_apply_r (first_node=0x38, parent_node=0x0, edit_node=0x55555578a260, parent_op=EDIT_REMOVE, diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, change=0x0)
    at /opt/dev/sysrepo/src/edit_diff.c:2363
2363	/opt/dev/sysrepo/src/edit_diff.c: No such file or directory.
(gdb) bt

#0  0x00007ffff7b82bdb in sr_edit_apply_r (first_node=0x38, parent_node=0x0, edit_node=0x55555578a260, parent_op=EDIT_REMOVE, diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, change=0x0)
    at /opt/dev/sysrepo/src/edit_diff.c:2363
#1  0x00007ffff7b83450 in sr_edit_apply_r (first_node=0x55555579c398, parent_node=0x55555579c360, edit_node=0x55555580fd00, parent_op=EDIT_ETHER, diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, 
    change=0x0) at /opt/dev/sysrepo/src/edit_diff.c:2526
#2  0x00007ffff7b83450 in sr_edit_apply_r (first_node=0x555555793278, parent_node=0x555555793240, edit_node=0x5555557e96d0, parent_op=EDIT_ETHER, diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, 
    change=0x0) at /opt/dev/sysrepo/src/edit_diff.c:2526
#3  0x00007ffff7b83450 in sr_edit_apply_r (first_node=0x5555557872c8, parent_node=0x555555787290, edit_node=0x555555790ba0, parent_op=EDIT_ETHER, diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, 
    change=0x0) at /opt/dev/sysrepo/src/edit_diff.c:2526
#4  0x00007ffff7b83450 in sr_edit_apply_r (first_node=0x7fffffffd8e0, parent_node=0x0, edit_node=0x55555578e000, parent_op=EDIT_CONTINUE, diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, change=0x0)
    at /opt/dev/sysrepo/src/edit_diff.c:2526
#5  0x00007ffff7b83614 in sr_edit_mod_apply (edit=0x55555578e000, ly_mod=0x5555557dffc0, oper_edit=1, data=0x7fffffffd8e0, diff=0x0, change=0x0) at /opt/dev/sysrepo/src/edit_diff.c:2571
#6  0x00007ffff7b7bc7e in sr_modinfo_get_filter (mod_info=0x7fffffffd8d0, xpath=0x555555555050 "/ietf-interfaces:interfaces/interface[name='eth0']/test1:c1/l1[k='item2']/v1", session=0x55555578abc0, 
    result=0x7fffffffd8c8) at /opt/dev/sysrepo/src/modinfo.c:2340
#7  0x00007ffff7b597c8 in sr_get_item (session=0x55555578abc0, path=0x555555555050 "/ietf-interfaces:interfaces/interface[name='eth0']/test1:c1/l1[k='item2']/v1", timeout_ms=30000, value=0x7fffffffd950)
    at /opt/dev/sysrepo/src/sysrepo.c:2351
#8  0x0000555555554e3c in main (argc=1, argv=0x7fffffffda48) at main.c:106
(gdb) 
```

sysrepo version: 2.1.26
libyang version: 2.0.148

Thanks!

**Comment by michalvasko** [comment]
Okay, should work now.
