### ISSUE TITLE
Sysrepoctl - Segmentation fault in sr_shmmod_recover_cb

### ISSUE THREAD

**Issue by Wexiwa** [sysrepo/sysrepo#2734]
Hi,

I am using sysrepo version v2.0.53 and I am getting a segfault while using syrepoctl.

Here's the back trace:

```
#0  0x00007ffff7b3e07f in sr_shmmod_recover_cb (mode=mode@entry=SR_LOCK_WRITE, cid=cid@entry=0, data=data@entry=0x7fffffffcb00)
    at src/shm_mod.c:393
#1  0x00007ffff7b1ce5a in sr_mlock (lock=lock@entry=0x7ffff7376008, timeout_ms=timeout_ms@entry=5000, func=func@entry=0x7ffff7b4f810 <__func__.12452> "sr_lydmods_conn_ctx_update", 
    cb=0x7ffff7b3e070 <sr_shmmod_recover_cb>, cb_data=cb_data@entry=0x7fffffffcb00)
    at src/common.c:3239
#2  0x00007ffff7b32df1 in sr_lydmods_lock (lock=lock@entry=0x7ffff7376008, ly_ctx=<optimized out>, func=func@entry=0x7ffff7b4f810 <__func__.12452> "sr_lydmods_conn_ctx_update")
    at src/lyd_mods.c:73
#3  0x00007ffff7b3323f in sr_lydmods_conn_ctx_update (conn=conn@entry=0x55555576abc0, ly_ctx=ly_ctx@entry=0x55555576abc0, apply_sched=1, err_on_sched_fail=0, changed=changed@entry=0x7fffffffccdc)
    at src/lyd_mods.c:2258
#4  0x00007ffff7b102d3 in sr_connect (opts=0, conn_p=0x7fffffffcd98) at src/sysrepo.c:198
```

My guess would be that `cb_data->ds_plg` pointer isn't properly set as it comes from `sr_lydmods_lock` where the member isn't set.

**Comment by michalvasko** [comment]
Yes, should be fixed by e932bad31d7a31ca6cba96651fd8f234cafaa802.

**Comment by Wexiwa** [comment]
Nice! Thank you for the quick answer!

Do you plane on making a release/tag for a newer version ? Or should I use the master branch regardless ?

**Comment by michalvasko** [comment]
We would like to make a release in a few weeks at the latest.
