### ISSUE TITLE
Crash while calling notification API notif_send

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2853]
Hi,
Following crash was seen in notif_send API call.
sysrepo version: 2.1.15
netopeer2-server version:  2.1.10
```
Program terminated with signal 11, Segmentation fault.
#0 0x00007f001b2be5cf in ?? ()
#0 0x00007f001b2be5cf in ?? ()
#1 0x0000000000000000 in ?? ()
Binary file Name : netopeer2-server
Binary file Name : netopeer2-server
Corefile file Name: core::ConfigMgrApp::1656054614
Corefile file Name: core::ConfigMgrApp::1656054614
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
...
Reading symbols from /opt/gNB/bin/ConfigMgrApp...done.
[New LWP 514]
[New LWP 499]
[New LWP 516]
[New LWP 517]
[New LWP 518]
[New LWP 519]
[New LWP 520]
[New LWP 527]
[New LWP 540]
[New LWP 1926]
[New LWP 500]
[New LWP 498]
[New LWP 501]
[New LWP 541]
[New LWP 497]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by ./ConfigMgrApp 255 255 8888 127.0.0.1'.
Program terminated with signal 11, Segmentation fault.
#0 0x00007f001b2be5cf in sr_edit_apply_r (first_node=0x38, parent_node=0x0,
edit_node=0x7f0004009870, parent_op=EDIT_REMOVE, diff_parent=0x0,
diff_root=0x0, oper_edit=1, flags=0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2342
#0 0x00007f001b2be5cf in sr_edit_apply_r (first_node=0x38, parent_node=0x0,
edit_node=0x7f0004009870, parent_op=EDIT_REMOVE, diff_parent=0x0,
diff_root=0x0, oper_edit=1, flags=0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2342
#1 0x00007f001b2bee1f in sr_edit_apply_r (first_node=0x7f0004004568,
parent_node=0x7f0004004530, edit_node=0x7f0004009930,
parent_op=EDIT_MERGE, diff_parent=0x0, diff_root=0x0, oper_edit=1,
flags=0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2505
#2 0x00007f001b2bee1f in sr_edit_apply_r (first_node=0x7f0004003fc8,
parent_node=0x7f0004003f90, edit_node=0x7f0004009510,
parent_op=EDIT_MERGE, diff_parent=0x0, diff_root=0x0, oper_edit=1,
flags=0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2505
#3 0x00007f001b2bee1f in sr_edit_apply_r (first_node=0x7f0004003a98,
parent_node=0x7f0004003a60, edit_node=0x7f00040093b0,
parent_op=EDIT_MERGE, diff_parent=0x0, diff_root=0x0, oper_edit=1,
flags=0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2505
#4 0x00007f001b2bee1f in sr_edit_apply_r (first_node=0x7f000fccbb50,
parent_node=0x0, edit_node=0x7f0004006ef0, parent_op=EDIT_CONTINUE,
diff_parent=0x0, diff_root=0x0, oper_edit=1, flags=0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2505
#5 0x00007f001b2befc1 in sr_edit_mod_apply (edit=0x7f0004006ef0,
ly_mod=0x24226b0, oper_edit=1, data=0x7f000fccbb50, diff=0x0, change=0x0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2550
#6 0x00007f001b2b35aa in sr_module_oper_data_update (mod=0x7f0004036490,
orig_name=0x0, orig_data=0x0, conn=0x2361b60, timeout_ms=60000, opts=0,
data=0x7f000fccbb50)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/modinfo.c:770
#7 0x00007f001b2b6909 in sr_modinfo_module_data_load (
mod_info=0x7f000fccbb40, mod=0x7f0004036490, orig_name=0x0,
orig_data=0x0, timeout_ms=60000, opts=0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/modinfo.c:1819
#8 0x00007f001b2b6f85 in sr_modinfo_data_load (mod_info=0x7f000fccbb40,
cache=4, orig_name=0x0, orig_data=0x0, timeout_ms=60000, opts=0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/modinfo.c:2000
#9 0x00007f001b2b727f in sr_modinfo_consolidate (mod_info=0x7f000fccbb40,
mod_deps=0, mod_lock=SR_LOCK_READ, mi_opts=37, sid=44, orig_name=0x0,
orig_data=0x0, timeout_ms=60000, ds_lock_timeout_ms=0, get_opts=0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/modinfo.c:2092
#10 0x00007f001b2a0c17 in sr_notif_send_tree (session=0x2464550,
notif=0x7f00040049f0, timeout_ms=2000, wait=0)
at /workspace/siqbuild/PRG-BUILDS/onecell_integration_6.5/CUCP/6.5.2.069/ran_3rdparty/open_source/netconf/sysrepo/src/sysrepo.c:5906
#11 0x0000000000445044 in event_notif_send_tree (notif=0x7f00040049f0,
this=0x7f00145be530) at ./src/ConfigMgrSysrepoInterface.cpp:268
#12 ConfigMgrSysrepoInterface::notif_send (this=0x7f00145be530,
notifXpath="/junila_3gpp-nr-nrm-nrcellcu:NrCellCU-state-info/NrCellCU_info[NrCellCU-id='1']",
notifAttrVec=std::vector of length 1, capacity 1 = {...})
at ./src/ConfigMgrSysrepoInterface.cpp:259
#13 0x000000000043ab4e in sendNotification (appId=,
moBlock=...) at ./src/ConfigMgrCallback.cpp:485
#14 0x0000000000437ad7 in handleNotificationUpdateMsg (pMsg=0x7f001538d440,
this=0x7f001538d440) at ./src/ConfigMgrApp.cpp:263
#15 ConfigMgrApp::processMessageFromQueue (this=this@entry=0x7f0013677370,
pMsg=0x7f001538d440) at ./src/ConfigMgrApp.cpp:212
#16 0x0000000000437d2c in ConfigMgrApp::run (this=0x7f0013677370)
at ./src/ConfigMgrApp.cpp:160
#17 0x000000000045a92d in LinuxThread::run (arg=0x7f0012b91898)
at ./src/LinuxThread.cpp:1279
#18 0x00007f001a281ea5 in start_thread () from /usr/lib64/libpthread.so.0
#19 0x00007f001937eb0d in clone () from /usr/lib64/libc.so.6'
```
Also attaching some logs just before crash time, in case that helps. We observed that there were almost like 214 notifications of the same attribute in some 14 seconds, before the crash happened. Not sure if too many notifications could be related to this crash.
Can you please help here.

[netopeer-sysrepo.log](https://github.com/sysrepo/sysrepo/files/8995727/netopeer-sysrepo.log)

**Comment by meghna-doshi** [comment]
Hi,
Any information here? We had some more queries on this.

**Comment by meghna-doshi** [comment]
Hi,
Do i have to report this issue somewhere else? Didnt get any update yet.

**Comment by meghna-doshi** [comment]
Hi,
Any update here please.

**Comment by michalvasko** [comment]
I seem to remember fixing this some time ago, so it should not occur in the latest version.

**Comment by meghna-doshi** [comment]
Hi Michal,
Can you please roughly tell us which file might have the fix, as upgrading to latest version wont be feasible right now. We will try taking the select fix.

**Comment by michalvasko** [comment]
You will have to find that out yourself, I really have no spare time dissecting all the commits looking for this fix.
