### ISSUE TITLE
Unable to get notification of changes of two modules at same time

### ISSUE THREAD

**Issue by shardulkumar79** [sysrepo/sysrepo#2896]
When there are changes in two different modules (_3gpp-common-managed-element and _3gpp-nr-nrm-rrmpolicy), then only the first module change is detected other change is failed at sr_get_change_next() with return value SR_ERR_NOT_FOUND. See in the log it prints  "error retrieving first change".

```
sr_session_ctx_t *sess;
sr_subscription_ctx_t *subscription;

static int custom_config_change_cb(sr_session_ctx_t* session, const char* module_name, const char* xpath, sr_event_t event, uint32_t request_id, void* private_data)
{
    int rc;
    (void)event;
    (void)module_name;
    (void)request_id;
    (void)xpath;
    FILE* fptr;

    char changePath[100];
    sprintf(changePath, "/%s//.", (char*)private_data);

    fptr = fopen("/cm.log", "a");
    fprintf(fptr, "val of private_data.....%s\n", private_data);
    fprintf(fptr, "val of changePath.....%s\n", changePath);
    fprintf(fptr, "val of module_name.....%s\n", module_name);
    if(xpath)
       fprintf(fptr, " val of xpath.....%s\n", xpath);
    else
       fprintf(fptr, " val of xpath is null.................\n");
    fclose(fptr);

    // get iterator for all changes
    sr_change_iter_t* iter;
    rc = sr_get_changes_iter(session, changePath, &iter);
    if (rc != SR_ERR_OK) {
        return rc;
    }

    sr_val_t* oldVal;
    sr_val_t* newVal;
    sr_val_t* tVal;
    sr_change_oper_t operation;
    char* hm_operation;


    // get first change
    rc = sr_get_change_next(session, iter, &operation, &oldVal, &newVal);
    if (rc != SR_ERR_OK) {
        fptr = fopen("/cm.log", "a");
        fprintf(fptr, "error retrieving first change\n");                    # ----> it is failing
        return rc;
    }
    fclose(fptr);


    char timeBuf[256];
    time_t rawtime;
    struct tm* info;
    time(&rawtime);
    info = localtime(&rawtime);
    strftime(timeBuf, 256, "%FT%TZ", info);
    int idx = 0;

    // iterate through other changes
    while (rc == SR_ERR_OK) {
        // write change information to file
        tVal = newVal;
        if(operation == SR_OP_DELETED) {
            tVal = oldVal;
        }

        // next change
        rc = sr_get_change_next(session, iter, &operation, &oldVal, &newVal);
        idx++;
    }

    sr_free_val(oldVal);
    sr_free_val(newVal);
    return SR_ERR_OK;

sr_error:
    sr_free_val(oldVal);
    sr_free_val(newVal);
    return rc;
}



int
sr_plugin_init_cb(sr_session_ctx_t *session, void **private_data)
{
    int rc;

    (void)private_data;

    /* remember the session of our plugin */
    sess = session;


    rc = sr_module_change_subscribe(session, "_3gpp-common-managed-element", NULL,
            custom_config_change_cb, "ManagedElement", 0,
            SR_SUBSCR_PASSIVE | SR_SUBSCR_DONE_ONLY, &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }

    rc = sr_module_change_subscribe(session, "_3gpp-nr-nrm-rrmpolicy", NULL,
            custom_config_change_cb, "RRMPolicyRatio", 0,
            SR_SUBSCR_PASSIVE | SR_SUBSCR_DONE_ONLY, &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }


    /* sysrepo/plugins.h provides an interface for logging */
    SRP_LOG_DBGMSG("OVEN: Oven plugin initialized successfully.");
    return SR_ERR_OK;

error:
    SRP_LOG_ERR("OVEN: Oven plugin initialization failed: %s.", sr_strerror(rc));
    sr_unsubscribe(subscription);
    return rc;
}

void
sr_plugin_cleanup_cb(sr_session_ctx_t *session, void *private_data)
{
    (void)session;
    (void)private_data;

    /* nothing to cleanup except freeing the subscriptions */
    sr_unsubscribe(subscription);
    SRP_LOG_DBGMSG("OVEN: Oven plugin cleanup finished.");
}](url)

```

Output

```
 in custom_config_change_cb.....
 val of private_data.....ManagedElement
 val of changePath...../ManagedElement//.
 val of module_name....._3gpp-common-managed-element
 val of xpath is null.................
 in custom_config_change_cb.....
 val of private_data.....RRMPolicyRatio
 val of changePath...../RRMPolicyRatio//.
 val of module_name....._3gpp-nr-nrm-rrmpolicy
 val of xpath is null.................
 error retrieving first change                       ---> this failed
```

RPC call
```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>0</id>
  <GNBCUCPFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbcucpfunction">
    <id>10001</id>
    <attributes>
      <vnfParametersList>
        <vnfInstanceId>3</vnfInstanceId>
        <vnfdId>0</vnfdId>
        <flavourId>0</flavourId>
        <autoScalable>true</autoScalable>
      </vnfParametersList>
    </attributes>
  </GNBCUCPFunction>
</ManagedElement>
<RRMPolicyRatio xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-rrmpolicy">
  <id>0</id>
  <attributes>
    <resourceType>PRB</resourceType>
    <rRMPolicyMaxRatio>70</rRMPolicyMaxRatio>
    <rRMPolicyMinRatio>30</rRMPolicyMinRatio>
    <rRMPolicyDedicatedRatio>50</rRMPolicyDedicatedRatio>
    <rRMPolicyMemberList>
      <mcc>404</mcc>
      <mnc>010</mnc>
      <sd>FFFFFF</sd>
      <sst>1</sst>
    </rRMPolicyMemberList>
  </attributes>
</RRMPolicyRatio>
```

Yang files:
```
/home/cprog/yang>cat _3gpp-common-managed-element.yang

module _3gpp-common-managed-element {
  yang-version 1.1;
  namespace urn:3gpp:sa5:_3gpp-common-managed-element;
  prefix "me3gpp";

  list ManagedElement {
    description "Represents telecommunications equipment or TMN entities within";
    key id;
    leaf id {
        type uint32;
    }
  }
}

/home/cprog/yang>cat  _3gpp-common-managed-function.yang

module _3gpp-common-managed-function {
  yang-version 1.1;
  namespace urn:3gpp:sa5:_3gpp-common-managed-function;
  prefix mf3gpp;


  grouping ManagedFunctionGrp {
    list vnfParametersList {
      key vnfInstanceId;

      leaf vnfInstanceId {
        type string ;
      }

      leaf vnfdId {
        type string ;
      }

      leaf flavourId {
        type string ;
      }

      leaf autoScalable {
        type boolean ;
        mandatory true;
      }
    }
  }
}


/home/cprog/yang>cat  _3gpp-nr-nrm-gnbcucpfunction.yang

module _3gpp-nr-nrm-gnbcucpfunction {
  yang-version 1.1;
  namespace "urn:3gpp:sa5:_3gpp-nr-nrm-gnbcucpfunction";
  prefix "gnbcucp3gpp";

  import _3gpp-common-managed-function { prefix mf3gpp; }
  import _3gpp-common-managed-element { prefix me3gpp; }


  grouping GNBCUCPFunctionGrp {
    uses mf3gpp:ManagedFunctionGrp;

    leaf gNBId {
      //mandatory true;
      type int64;
      default 1;
    }
  }

  augment "/me3gpp:ManagedElement" {

    list GNBCUCPFunction {
      description "Represents the logical function CU-CP of gNB and en-gNB.";
      key id;
      leaf id {
          type uint32;
      }
      container attributes {
        uses GNBCUCPFunctionGrp;
      }
    }
  }
}



/home/cprog/yang> cat _3gpp-nr-nrm-rrmpolicy.yang

module _3gpp-nr-nrm-rrmpolicy {
  yang-version 1.1;
  namespace "urn:3gpp:sa5:_3gpp-nr-nrm-rrmpolicy";
  prefix nrrrmpolicy3gpp;

  typedef Mcc {
    type string {
      pattern '[02-79][0-9][0-9]';
    }
  }

  typedef Mnc {
    type string {
      pattern '[0-9][0-9][0-9]|[0-9][0-9]';
    }
  }

  grouping SNssai {
    leaf sd {
      type string{
        length 6;
        pattern '[a-fA-F0-9]*';
      }
    }

    leaf sst {
      type uint8;
    }
  }

  grouping PLMNId {
    leaf mcc {
      mandatory true;
      type Mcc;
    }
    leaf mnc {
      mandatory true;
      type Mnc;
    }
  }

  grouping PLMNInfo {
    uses PLMNId;
    uses SNssai;
  }


  grouping rRMPolicyMemberGrp {
    uses PLMNInfo;
  }

  grouping RRMPolicy_Grp {
    leaf resourceType {
      mandatory true;
      type string;
    }

    list rRMPolicyMemberList{
      min-elements 1;
      key "mcc mnc sd sst";
      uses rRMPolicyMemberGrp;
    }
  }

  grouping RRMPolicyRatioGrp {
    uses RRMPolicy_Grp;    // Inherits RRMPolicy_
    leaf rRMPolicyMaxRatio {
      default 100;
      type uint8 { range "0..100"; }
      units percent;
    }

    leaf rRMPolicyMinRatio {
      default 0;
      type uint8 { range "0..100"; }
      units percent;
    }

    leaf rRMPolicyDedicatedRatio {
      default 0;
      type uint8 { range "0..100"; }
      units percent;
      }
    }

  list RRMPolicyRatio {
    key id;
    leaf id {
           type uint32;
    }
    container attributes {
      uses RRMPolicyRatioGrp;
    }
  }
}




```

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? Seems like an obsolete one.

**Comment by shardulkumar79** [comment]
> What _sysrepo_ version are you using? Seems like an obsolete one.

I am using  sysrepo v1.4.140

**Comment by michalvasko** [comment]
Then like I said, it is obsolete and no longer supported.

**Comment by shardulkumar79** [comment]
> Then like I said, it is obsolete and no longer supported

could you please let me know the minimum latest version which is supported?  i saw somewhere in the forum there is some issue with               sr_get_changes_iter(session, "**/example-module//.**" , &it);     or    sr_get_changes_iter(session, "**/example-module:*//.**" , &it);                   but both did not work in my case.

**Comment by michalvasko** [comment]
Version 1.4.140 is pretty much the latest v1. So, you will need to update to v2, in which case there is no reason not to take the latest release version 2.1.84.

**Comment by shardulkumar79** [comment]
Hi @michalvasko, when I have upgraded sysrepo 2.1.84 to latest version and try to get simultaneous notation on both ManagedElement and RRMPolicyRatio   modules I get below crash. I could not understand the reason for this. Could you please help me with this?

```
root@aaff1d3f5549:/opt/dev# gdb   sysrepo-plugind
Reading symbols from sysrepo-plugind...
(No debugging symbols found in sysrepo-plugind)
(gdb) r -d v4

(gdb)
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007fe7c79c9d15 in __vfprintf_internal (s=s@entry=0x7fe7c75e28e0, format=format@entry=0x7fe7c7ca6000 "/%s//.", ap=ap@entry=0x7fe7c75e2a20, mode_flags=mode_flags@entry=6)
    at vfprintf-internal.c:1688
#2  0x00007fe7c79d60f9 in __vsprintf_internal (string=0x7fe7c75e2b20 "/\300_\307\347\177", maxlen=<optimized out>, format=0x7fe7c7ca6000 "/%s//.", args=args@entry=0x7fe7c75e2a20,
    mode_flags=6) at iovsprintf.c:95
#3  0x00007fe7c7a7ee4b in ___sprintf_chk (s=<optimized out>, flag=<optimized out>, slen=<optimized out>, format=<optimized out>) at sprintf_chk.c:40
#4  0x00007fe7c7ca528a in custom_config_change_cb () from /usr/local/lib/sysrepo-plugind/plugins/oven.so
#5  0x00007fe7c7c64ae7 in sr_shmsub_change_listen_process_module_events () from /usr/local/lib/libsysrepo.so.7
#6  0x00007fe7c7c2df1a in sr_subscription_process_events () from /usr/local/lib/libsysrepo.so.7
#7  0x00007fe7c7c66ec1 in sr_shmsub_listen_thread () from /usr/local/lib/libsysrepo.so.7
#8  0x00007fe7c7b4b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fe7c7a70133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

I have written my own version of  custom_config_change_cb() callback. This is a minimalistic implementation where I want to play around with two apis namely  sr_get_changes_iter() and sr_get_change_next(). My objective is to introduce  changes in two different modules and handle them with these apis.


```
static int custom_config_change_cb(sr_session_ctx_t* session, const char* module_name, const char* xpath, sr_event_t event, uint32_t request_id, void* private_data)
{
    int rc;
    (void)event;
    (void)module_name;
    (void)request_id;
    (void)xpath;

    char changePath[100];
    sprintf(changePath, "/%s//.", (char*)private_data);

    // get iterator for all changes
    sr_change_iter_t* iter;
    rc = sr_get_changes_iter(session, changePath, &iter);
    if (rc != SR_ERR_OK) {
        printf("error in iteration.....\n");
        return rc;
    }

    sr_val_t* oldVal;
    sr_val_t* newVal;
    sr_val_t* tVal;
    sr_change_oper_t operation;
    char* hm_operation;


    // get first change
    rc = sr_get_change_next(session, iter, &operation, &oldVal, &newVal);
    if (rc != SR_ERR_OK) {
        printf("error retrieving first change\n");
        return rc;
    }


    int idx = 0;
    // iterate through other changes
    while (rc == SR_ERR_OK) {
        // write change information to file
        tVal = newVal;
        if(operation == SR_OP_DELETED) {
            tVal = oldVal;
        }

        // next change
        rc = sr_get_change_next(session, iter, &operation, &oldVal, &newVal);
        idx++;
    }

    sr_free_val(oldVal);
    sr_free_val(newVal);
    return SR_ERR_OK;

sr_error:
    sr_free_val(oldVal);
    sr_free_val(newVal);
    return rc;
}

int
sr_plugin_init_cb(sr_session_ctx_t *session, void **private_data)
{
    int rc;

    (void)private_data;

    /* remember the session of our plugin */
    sess = session;


    rc = sr_module_change_subscribe(session, "_3gpp-common-managed-element", NULL,
            custom_config_change_cb, "ManagedElement", 0,
            SR_SUBSCR_PASSIVE | SR_SUBSCR_DONE_ONLY, &subscription);
            //SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }

    rc = sr_module_change_subscribe(session, "_3gpp-nr-nrm-rrmpolicy", NULL,
            custom_config_change_cb, "RRMPolicyRatio", 0,
            SR_SUBSCR_PASSIVE | SR_SUBSCR_DONE_ONLY, &subscription);
            //SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }


    /* sysrepo/plugins.h provides an interface for logging */
    SRPLG_LOG_DBG("oven", "Oven plugin initialized successfully.");
    return SR_ERR_OK;

error:
    SRPLG_LOG_ERR("oven", "Oven plugin initialization failed: %s.", sr_strerror(rc));
    sr_unsubscribe(subscription);
    return rc;
}
```

**Comment by michalvasko** [comment]
Recompile your plugin and do not ignore the warnings, then it will not crash.

**Comment by shardulkumar79** [comment]
> sysrepo v1.4.140

hi @michalvasko as you said that this is bug in sysrepo v1.4.140   do you have an idea when and in which version this issue got fixed? I would like to try back porting this fix in to my old repo. As upgrading, syrepo lasted v2 has other challenges for me.
