### ISSUE TITLE
`sr_oper_delete_item_str` change of behavior

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2952]
I'm trying to port the test suite of sysrepo-cpp to the new version of sysrepo. Previously, we checked that `sr_oper_delete_item_str` cannot use a `NULL` value string; that's no longer the case because that function now just wraps `sr_delete_item`. However, if I change my test so that it simply calls `sr_delete_item` ([this is our diff](https://gerrit.cesnet.cz/plugins/gitiles/CzechLight/sysrepo-cpp/+/7e298c9ef72a733f1523e71e1934b8c7015654a3%5E%21/)), then I get en error message from libyang:
```
2/9 Test #1: test_session .....................***Failed    0.14 sec
[INF] Connection 2 created.
[INF] Session 1 (user "jkt", CID 2) created.
[INF] No datastore changes to apply.
[INF] No datastore changes to apply.
[INF] Connection 3 created.
[INF] Session 2 (user "jkt", CID 3) created.
[INF] No datastore changes to apply.
[INF] There are no subscribers for changes of the module "test_module" in running DS.
[INF] Connection 4 created.
[INF] Session 3 (user "jkt", CID 4) created.
[INF] No datastore changes to apply.
[INF] No datastore changes to apply.
[INF] Connection 5 created.
[INF] Session 4 (user "jkt", CID 5) created.
[INF] There are no subscribers for changes of the module "test_module" in running DS.
[INF] There are no subscribers for changes of the module "test_module" in running DS.
[INF] There are no subscribers for changes of the module "test_module" in running DS.
[INF] There are no subscribers for changes of the module "test_module" in running DS.
[ERR] Not found node "non-existent" in path.
[ERR] Invalid datastore edit.
[INF] No datastore changes to apply.
[INF] Connection 6 created.
[INF] Session 5 (user "jkt", CID 6) created.
[INF] No datastore changes to apply.
[INF] There are no subscribers for changes of the module "test_module" in running DS.
[ERR] Cannot add metadata "sysrepo:cid" to an opaque node "leafInt32".
[INF] No datastore changes to apply.

[...non-relevant doctest chatter removed...]

ERROR: test case THREW exception: Session::applyChanges: Couldn't apply changes: SR_ERR_LY
```
The test code looks like this:
```c++
sysrepo::setLogLevelStderr(sysrepo::LogLevel::Information);
std::optional<sysrepo::Connection> conn{std::in_place};
auto sess = conn->sessionStart();
sess.copyConfig(sysrepo::Datastore::Startup);
        
// Set some arbitrary leaf.
sess.setItem("/test_module:leafInt32", "123");
sess.applyChanges();

// The leaf is accesible from the running datastore.
REQUIRE(sess.getData("/test_module:leafInt32")->asTerm().valueStr() == "123");

// The leaf is NOT accesible from the operational datastore without a subscription.
sess.switchDatastore(sysrepo::Datastore::Operational);
REQUIRE(!sess.getData("/test_module:leafInt32"));

// When we create a subscription, the leaf is accesible from the operational datastore.
sess.switchDatastore(sysrepo::Datastore::Running);
auto sub = sess.onModuleChange("test_module", [] (auto, auto, auto, auto, auto, auto) {
    return sysrepo::ErrorCode::Ok; });
sess.switchDatastore(sysrepo::Datastore::Operational);
REQUIRE(sess.getData("/test_module:leafInt32")->asTerm().valueStr() == "123");

// After using deleteItem, the leaf is no longer accesible from the operational datastore.
sess.deleteItem("/test_module:leafInt32");




/*************************** the following thing fails ****************************/
sess.applyChanges();
/*************************** ...and I don't know why. ****************************/






REQUIRE(!sess.getData("/test_module:leafInt32"));

// Using discardOperationalChanges makes the leaf visible again (in the operational datastore).
conn->discardOperationalChanges("/test_module:leafInt32");
REQUIRE(sess.getData("/test_module:leafInt32")->asTerm().valueStr() == "123");
```

**Comment by jktjkt** [comment]
Thanks for a quick fix and for adding a regression test. After the update, I get the following undefined behavior (note that extra libyang error) when trying to *discard* the operational changes (same test as the example shown above):
```
[ERR] Invalid identityref "ietf-origin:unknown" value - unable to map prefix to YANG schema.
/home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xpath.c:9546:36: runtime error: member access within null pointer of type 'const struct lysc_node'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xpath.c:9546:36 in 
[doctest] doctest version is "2.4.6"
[doctest] run with "--help" for options
===============================================================================
/home/jkt/work/cesnet/gerrit/CzechLight/sysrepo-cpp/tests/session.cpp:15:
TEST CASE:  session
  Session::deleteOperItem

/home/jkt/work/cesnet/gerrit/CzechLight/sysrepo-cpp/tests/session.cpp:15: FATAL ERROR: test case CRASHED: SIGSEGV - Segmentation violation signal

===============================================================================
/home/jkt/work/cesnet/gerrit/CzechLight/sysrepo-cpp/tests/session.cpp:15:
TEST CASE:  session

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  Session::deleteOperItem

===============================================================================
[doctest] test cases:  1 |  0 passed | 1 failed | 0 skipped
[doctest] assertions: 12 | 12 passed | 0 failed |
[doctest] Status: FAILURE!
AddressSanitizer:DEADLYSIGNAL
=================================================================
==359865==ERROR: AddressSanitizer: SEGV on unknown address 0x03e800057db9 (pc 0x7f61e22bd792 bp 0x7fff595ac980 sp 0x7fff595ac880 T0)
==359865==The signal is caused by a READ memory access.
    #0 0x7f61e22bd792 in lyxp_eval /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xpath.c
    #1 0x7f61e1e98ca9 in lyd_find_xpath4 /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:2695:11
    #2 0x7f61e1e99d5c in lyd_find_xpath /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:2754:12
    #3 0x7f61e7a03605 in sr_edit_oper_del /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/edit_diff.c:3422:13
    #4 0x7f61e79256dc in sr_discard_oper_changes /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/sysrepo.c:561:21
    #5 0x7f61e82ab73c in sysrepo::Connection::discardOperationalChanges(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, std::optional<sysrepo::Session>, std::chrono::duration<long, std::ratio<1l, 1000l> >) /home/jkt/work/cesnet/gerrit/CzechLight/sysrepo-cpp/src/Connection.cpp:61:16
    #6 0x523231 in DOCTEST_ANON_FUNC_2() /home/jkt/work/cesnet/gerrit/CzechLight/sysrepo-cpp/tests/session.cpp:91:15
    #7 0x547549 in doctest::Context::run() /home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/target/include/doctest/doctest.h:6510:21
    #8 0x54c7f6 in main /home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/target/include/doctest/doctest.h:6595:71
    #9 0x7f61e7c2b236 in __libc_start_call_main (/nix/store/v6szn6fczjbn54h7y40aj7qjijq7j6dc-glibc-2.34-210/lib/libc.so.6+0x29236) (BuildId: fcc74e6d20f2fb15ea41bcd03c49d1a9f6a65ac7)
    #10 0x7f61e7c2b2f4 in __libc_start_main@GLIBC_2.2.5 (/nix/store/v6szn6fczjbn54h7y40aj7qjijq7j6dc-glibc-2.34-210/lib/libc.so.6+0x292f4) (BuildId: fcc74e6d20f2fb15ea41bcd03c49d1a9f6a65ac7)
    #11 0x42a320 in _start /build/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xpath.c in lyxp_eval
```

**Comment by michalvasko** [comment]
I should have tested that, too, but did not expect additional problems. But there were quite a lot of them and I seemed to have had a good reason why the value was required for oper data deletes, too late now. So this use-case was added to tests and should work as well.

**Comment by jktjkt** [comment]
thanks
