### ISSUE TITLE
heap-buffer-overflow when installing already-installed modules

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#3032]
When I try to (re)install a module which has been already installed before, the installation crashes. I'm on the latest `devel` of everything. Also, I'm installing two modules at once.
```console-session
[nix-shell:~/work/prog/_build/czechlight-clang15-asan-ubsan]$ sysrepoctl --install ~/work/cesnet/gerrit/CzechLight/velia/yang/ietf-interfaces@2018-02-20.yang --install ~/work/cesnet/gerrit/CzechLight/velia/yang/ietf-ip@2018-02-22.yang

[nix-shell:~/work/prog/_build/czechlight-clang15-asan-ubsan]$ sysrepoctl --install ~/work/cesnet/gerrit/CzechLight/velia/yang/ietf-interfaces@2018-02-20.yang --install ~/work/cesnet/gerrit/CzechLight/velia/yang/ietf-ip@2018-02-22.yang
=================================================================
==1358733==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x610000013700 at pc 0x55f9f1e749aa bp 0x7ffcaabef190 sp 0x7ffcaabee950
READ of size 192 at 0x610000013700 thread T0
    #0 0x55f9f1e749a9 in __asan_memmove (/home/jkt/work/prog/_build/czechlight-clang15-asan-ubsan/target/bin/sysrepoctl+0xd89a9)
    #1 0x7f43fe72803c in _sr_install_modules github/sysrepo/sysrepo/src/sysrepo.c:1434:17
    #2 0x7f43fe72a52e in sr_install_modules2 github/sysrepo/sysrepo/src/sysrepo.c:1608:10
    #3 0x55f9f1ebbec6 in main github/sysrepo/sysrepo/src/executables/sysrepoctl.c:914:18
    #4 0x7f43fd42924d in __libc_start_call_main (/nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6+0x2924d) (BuildId: 5f9c93175ddddd93d3113da37a2f99ce5d4ba14a)
    #5 0x7f43fd429308 in __libc_start_main@GLIBC_2.2.5 (/nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6+0x29308) (BuildId: 5f9c93175ddddd93d3113da37a2f99ce5d4ba14a)
    #6 0x55f9f1dc34e4 in _start (/home/jkt/work/prog/_build/czechlight-clang15-asan-ubsan/target/bin/sysrepoctl+0x274e4)

0x610000013700 is located 0 bytes to the right of 192-byte region [0x610000013640,0x610000013700)
allocated by thread T0 here:
LLVMSymbolizer: error reading file: No such file or directory
    #0 0x55f9f1e763e7 in __interceptor_calloc (/home/jkt/work/prog/_build/czechlight-clang15-asan-ubsan/target/bin/sysrepoctl+0xda3e7)
    #1 0x7f43fe72a43e in sr_install_modules2 github/sysrepo/sysrepo/src/sysrepo.c:1598:16
    #2 0x55f9f1ebbec6 in main github/sysrepo/sysrepo/src/executables/sysrepoctl.c:914:18
    #3 0x7f43fd42924d in __libc_start_call_main (/nix/store/2j8jqmnd9l7plihhf713yf291c9vyqjm-glibc-2.35-224/lib/libc.so.6+0x2924d) (BuildId: 5f9c93175ddddd93d3113da37a2f99ce5d4ba14a)
    #4 0x7ffcaabf1835  ([stack]+0x20835)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/jkt/work/prog/_build/czechlight-clang15-asan-ubsan/target/bin/sysrepoctl+0xd89a9) in __asan_memmove
Shadow bytes around the buggy address:
  0x0c207fffa690: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c207fffa6a0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c207fffa6b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c207fffa6c0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c207fffa6d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c207fffa6e0:[fa]fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c207fffa6f0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c207fffa700: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c207fffa710: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c207fffa720: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c207fffa730: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1358733==ABORTING
```

**Comment by michalvasko** [comment]
Sorry about that, should be fixed.
