### ISSUE TITLE
Segmentation fault in sr_modinfo_collect_edit during edit-config

### ISSUE THREAD

**Issue by farafilka** [sysrepo/sysrepo#3070]
Hello,

I have faced with segmentation fault during `edit-config` operation with such params:
```
<edit-config>
 <target>
  <candidate></candidate>
 </target>
<default-operation>replace</default-operation>
```
Trace from `gdb`:
```
Thread 2 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f129791f700 (LWP 26)]
sr_modinfo_collect_edit (edit=0x7f128403a490, mod_info=0x7f129791ea40) at /sysrepo/src/modinfo.c:155
155     /sysrepo/src/modinfo.c: No such file or directory.

(gdb) bt
#0  sr_modinfo_collect_edit (edit=0x7f128403a490, mod_info=0x7f129791ea40) at /sysrepo/src/modinfo.c:155
#1  0x00007f129802dbef in sr_apply_changes (session=0x7f129000f0a0, timeout_ms=5000) at /sysrepo/src/sysrepo.c:3465
#2  0x000056209bf5ea19 in np2srv_rpc_editconfig_cb (session=0x7f128402da20, UNUSED_sub_id=2, UNUSED_op_path=0x56209c7e6250 "/ietf-netconf:edit-config", input=0x7f12840027c0, event=SR_EV_RPC, 
    UNUSED_request_id=1, UNUSED_output=0x7f1284019180, UNUSED_private_data=0x0) at /netopeer2/src/netconf.c:281
#3  0x00007f1298074cc9 in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x56209c7e75f0, ev_sess=0x7f128402da20, input_op=0x7f12840027c0, event=SR_SUB_EV_RPC, request_id=1, 
    output_op=0x7f129791ec70, err_code=0x7f129791ec38) at /sysrepo/src/shm_sub.c:3062
#4  0x00007f1298075a4c in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x56209c6be6f0, conn=0x56209c68bbc0) at /sysrepo/src/shm_sub.c:3347
#5  0x00007f129802f794 in sr_subscription_process_events (subscription=0x56209c69cdc0, session=0x0, stop_time_in=0x7f129791edd0) at /sysrepo/src/sysrepo.c:4098
#6  0x00007f1298076c5d in sr_shmsub_listen_thread (arg=0x56209c69cdc0) at /sysrepo/src/shm_sub.c:3783
#7  0x00007f1298226609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f1297f46133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

libsysrepo v2.1.84
netopeer2-server 2.1.36

**Comment by michalvasko** [comment]
Fixed in *sysrepo* version 2.2.38.
