### ISSUE TITLE
Segmentation fault when pushing operational data

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3253]
Hi,

I ran into a segmentation fault when trying to push operational data parallel.
I found that it is caused by race condition on `oper_push_mods` of `sr_conn_ctx_t`, the functions
`sr_conn_push_oper_mod_add` and `sr_conn_push_oper_mod_del` modify it without locking.
 
I attached an example application to reproduce it, in a short time it crashes or aborts:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/14418747/reprod.zip)
 
```
$ ./reprod  
================================================================= 
==1279096==ERROR: AddressSanitizer: attempting double-free on 0x602000118910 in thread T3: 
   #0 0x7fa819713c3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163                                                                                                                                     
   #1 0x7fa819554295 in sr_conn_push_oper_mod_add /opt/dev/sysrepo/src/common.c:5394 
   #2 0x7fa819568b78 in sr_modinfo_data_store /opt/dev/sysrepo/src/modinfo.c:3396 
   #3 0x7fa81953d508 in sr_changes_notify_store /opt/dev/sysrepo/src/sysrepo.c:3812 
   #4 0x7fa81953d873 in sr_apply_changes /opt/dev/sysrepo/src/sysrepo.c:3889 
   #5 0x55955a798882 in edit_interfaces reprod.c:49 
   #6 0x7fa8195eb608 in start_thread /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:477 
   #7 0x7fa8192bb352 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f352)
```

libyang version: 2.2.0
sysrepo version: 2.2.156

Thank you in advance!

**Comment by michalvasko** [comment]
Right, should be fixed.

**Comment by awesomenode** [comment]
I cannot reproduce it on latest version, thank you!
