### ISSUE TITLE
Memory leak when inserting into a user ordered list after a nonexistent key

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#3291]
Hello, 

lsan reports leaks in the following C code that tries to insert element into user-ordered list at a position after a key that does not exist. Note that the code does not leak when the key exists.

The yang module:

```yang
module example {
  yang-version 1.1;
  namespace "http://example.tld/example";
  prefix ex;

  container ordered-lists {
    list lst {
      ordered-by user;
      key "name";
      leaf name { type string; }
    }
  }
}
```

The code:

```cpp
#include <cassert>
#include <libyang/libyang.h>
#include <sysrepo.h>

auto INPUT = R"(
{
  "example:ordered-lists": {
    "lst": [
      {
        "@": {
          "ietf-netconf:operation": "create",
          "yang:insert": "after",
          "yang:key": "[name='bar']"
        },
        "name": "foo"
      }
    ]
  }
}
)";

void print(lyd_node* node)
{
    lyd_print_file(stdout, node, LYD_JSON, LYD_PRINT_WD_ALL | LYD_PRINT_WITHSIBLINGS);
}

int main()
{
    sr_conn_ctx_t* connection;
    sr_session_ctx_t* session;
    sr_log_stderr(SR_LL_DBG);
    ly_log_level(LY_LLDBG);

    assert(sr_connect(0, &connection) == SR_ERR_OK);
    assert(sr_session_start(connection, SR_DS_RUNNING, &session) == SR_ERR_OK);
    const ly_ctx* ctx = sr_session_acquire_context(session);

    lyd_node* edit;
    assert(lyd_parse_data_mem(ctx, INPUT, LYD_JSON, LYD_PARSE_STRICT | LYD_PARSE_NO_STATE | LYD_PARSE_ONLY, 0, &edit) == LY_SUCCESS);
    print(edit);

    assert(sr_edit_batch(session, edit, "merge") == SR_ERR_OK);
    assert(sr_apply_changes(session, 0) == SR_ERR_NOT_FOUND);
    lyd_free_all(edit);

    sr_session_stop(session);
    sr_disconnect(connection);
}
```

and output:

```
$ clang -fsanitize=address,undefined -g (...) test.cpp &&   ./a.out 
[INF] Connection 2 created.
[INF] Session 1 (user "tomas", CID 2) created.
{
  "example:ordered-lists": {
    "lst": [
      {
        "@": {
          "ietf-netconf:operation": "create",
          "yang:insert": "after",
          "yang:key": "[name='bar']"
        },
        "name": "foo"
      }
    ]
  }
}
[ERR] Node "lst" instance to insert next to not found.
[ERR] Applying operation "create" failed.
libyang[1]: String "foo" not freed from the dictionary, refcount 1.

=================================================================
==2812540==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x616d1c1fb6a1 in calloc (/home/tomas/zdrojaky/cesnet/tmp/a.out+0x11a6a1) (BuildId: d5f9f312a472f044d202d83f95a0064dd3afe324)
    #1 0x79ae1e38b61e in lyd_dup_r /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2060:19
    #2 0x79ae1e38f008 in lyd_dup_r /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2158:17
    #3 0x79ae1e35a1d7 in lyd_dup /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2347:18
    #4 0x79ae1e357fc5 in lyd_dup_single /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2410:12
    #5 0x79ae1d854c7d in sr_lyd_dup /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/ly_wrap.c:882:16
    #6 0x79ae1d90e72a in sr_edit_apply_move /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:1867:25
    #7 0x79ae1d8ea0c6 in sr_edit_apply_r /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:2349:29
    #8 0x79ae1d8eaf73 in sr_edit_apply_r /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:2425:25
    #9 0x79ae1d8e7af2 in sr_edit_mod_apply /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:2462:25
    #10 0x79ae1d8a8899 in sr_modinfo_edit_apply /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/modinfo.c:585:25
    #11 0x79ae1d7ab017 in sr_apply_changes /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/sysrepo.c:3893:20
    #12 0x616d1c2436e9 in main /home/tomas/zdrojaky/cesnet/tmp/test.cpp:43:5
    #13 0x79ae1d441d49  (/usr/lib/libc.so.6+0x25d49) (BuildId: 915eeec6439cfded1125deefc44a8d73e57873d9)
    #14 0x79ae1d441e0b in __libc_start_main (/usr/lib/libc.so.6+0x25e0b) (BuildId: 915eeec6439cfded1125deefc44a8d73e57873d9)
    #15 0x616d1c10c154 in _start (/home/tomas/zdrojaky/cesnet/tmp/a.out+0x2b154) (BuildId: d5f9f312a472f044d202d83f95a0064dd3afe324)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x616d1c1fb6a1 in calloc (/home/tomas/zdrojaky/cesnet/tmp/a.out+0x11a6a1) (BuildId: d5f9f312a472f044d202d83f95a0064dd3afe324)
    #1 0x79ae1e38b606 in lyd_dup_r /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2056:19
    #2 0x79ae1e35a1d7 in lyd_dup /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2347:18
    #3 0x79ae1e357fc5 in lyd_dup_single /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:2410:12
    #4 0x79ae1d854c7d in sr_lyd_dup /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/ly_wrap.c:882:16
    #5 0x79ae1d90e72a in sr_edit_apply_move /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:1867:25
    #6 0x79ae1d8ea0c6 in sr_edit_apply_r /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:2349:29
    #7 0x79ae1d8eaf73 in sr_edit_apply_r /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:2425:25
    #8 0x79ae1d8e7af2 in sr_edit_mod_apply /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/edit_diff.c:2462:25
    #9 0x79ae1d8a8899 in sr_modinfo_edit_apply /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/modinfo.c:585:25
    #10 0x79ae1d7ab017 in sr_apply_changes /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/sysrepo.c:3893:20
    #11 0x616d1c2436e9 in main /home/tomas/zdrojaky/cesnet/tmp/test.cpp:43:5
    #12 0x79ae1d441d49  (/usr/lib/libc.so.6+0x25d49) (BuildId: 915eeec6439cfded1125deefc44a8d73e57873d9)
    #13 0x79ae1d441e0b in __libc_start_main (/usr/lib/libc.so.6+0x25e0b) (BuildId: 915eeec6439cfded1125deefc44a8d73e57873d9)
    #14 0x616d1c10c154 in _start (/home/tomas/zdrojaky/cesnet/tmp/a.out+0x2b154) (BuildId: d5f9f312a472f044d202d83f95a0064dd3afe324)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x616d1c1fb339 in malloc (/home/tomas/zdrojaky/cesnet/tmp/a.out+0x11a339) (BuildId: d5f9f312a472f044d202d83f95a0064dd3afe324)
    #1 0x79ae1e29fd18 in dict_insert /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/dict.c:209:28
    #2 0x79ae1e2a0610 in lydict_insert /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/dict.c:248:14
    #3 0x79ae1ebfa7cc in lyplg_type_store_string /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/plugins_types/string.c:90:15
    #4 0x79ae1e3ab6de in lyd_value_store /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data_common.c:532:11
    #5 0x79ae1e3d1ce3 in lyd_create_term /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data_new.c:71:11
    #6 0x79ae1e718c20 in lyd_parser_create_term /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_common.c:289:14
    #7 0x79ae1e4465c8 in lydjson_parse_instance /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1506:17
    #8 0x79ae1e436cac in lydjson_subtree_r /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1767:17
    #9 0x79ae1e4516ad in lydjson_parse_instance_inner /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1425:13
    #10 0x79ae1e446e42 in lydjson_parse_instance /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1523:17
    #11 0x79ae1e4364ad in lydjson_subtree_r /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1743:21
    #12 0x79ae1e4516ad in lydjson_parse_instance_inner /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1425:13
    #13 0x79ae1e446e42 in lydjson_parse_instance /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1523:17
    #14 0x79ae1e436cac in lydjson_subtree_r /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1767:17
    #15 0x79ae1e430975 in lyd_parse_json /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/parser_json.c:1881:13
    #16 0x79ae1e336798 in lyd_parse /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:132:13
    #17 0x79ae1e33798a in lyd_parse_data /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:222:12
    #18 0x79ae1e337b33 in lyd_parse_data_mem /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:233:11
    #19 0x616d1c2435a5 in main /home/tomas/zdrojaky/cesnet/tmp/test.cpp:39:5
    #20 0x79ae1d441d49  (/usr/lib/libc.so.6+0x25d49) (BuildId: 915eeec6439cfded1125deefc44a8d73e57873d9)
    #21 0x79ae1d441e0b in __libc_start_main (/usr/lib/libc.so.6+0x25e0b) (BuildId: 915eeec6439cfded1125deefc44a8d73e57873d9)
    #22 0x616d1c10c154 in _start (/home/tomas/zdrojaky/cesnet/tmp/a.out+0x2b154) (BuildId: d5f9f312a472f044d202d83f95a0064dd3afe324)

SUMMARY: AddressSanitizer: 172 byte(s) leaked in 3 allocation(s).
```

**Comment by michalvasko** [comment]
Fixed, thanks.

**Comment by peckato1** [comment]
thanks, it works.
