### ISSUE TITLE
Memory leak when subscribing to notifications filtered by NACM

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#3322]
Hi,

during one of our test runs I have seen this leak sanitizer report. 

The test subscribes for notifications. Some of the notifications are denied for the client because of NACM rules.

```
Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x560ba2a0b292 in strdup (/home/tomas/zdrojaky/cesnet/rousette/build-clang-asan/test-restconf-notifications+0x224292) (BuildId: 7f6c2e279268b09337926307cbdc7bb86e5ba0fe)
    #1 0x7feb7fa5d2a1 in sr_nacm_check_operation /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/utils/nacm.c:1785:36
    #2 0x7feb7fa09fa9 in sr_shmsub_notif_listen_process_module_events /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/shm_sub.c:4672:53
    #3 0x7feb7f7ba8aa in sr_subscription_process_events /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/sysrepo.c:4642:25
    #4 0x7feb7fa0d79d in sr_shmsub_listen_thread /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/shm_sub.c:4873:15
    #5 0x560ba2948bf6 in asan_thread_start(void*) asan_interceptors.cpp.o

SUMMARY: AddressSanitizer: 3 byte(s) leaked in 1 allocation(s).
```

Using sysrepo [73ec45d7](https://github.com/sysrepo/sysrepo/commit/73ec45d7184c7a5216dd8e609a68423188eb3018)

**Comment by michalvasko** [comment]
Right, thanks, fixed.

**Comment by peckato1** [comment]
Wow, that was fast. Thanks.
