### ISSUE TITLE
crash in sr_change_ly2sr due to LYS_ANYXML

### ISSUE THREAD

**Issue by irfanHaslanded** [sysrepo/sysrepo#3336]
```c
#define LYS_ANYXML      0x0020    /**< anyxml statement node */
```

```c
(gdb) p/x node->schema->nodetype
$3 = 0x20
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7d9de8f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7d4efb2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7d39472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7d39395 in __assert_fail_base (fmt=0x7ffff7eada90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7ffff7f8ed20 "node->schema->nodetype & (LYS_LEAF | LYS_LEAFLIST)", file=file@entry=0x7ffff7f8e000 "/home/irfan/opensource/sysrepo/src/sysrepo.c",
    line=line@entry=5581, function=function@entry=0x7ffff7f8fa50 <__PRETTY_FUNCTION__.19> "sr_change_ly2sr") at ./assert/assert.c:92
#5  0x00007ffff7d47eb2 in __GI___assert_fail (assertion=0x7ffff7f8ed20 "node->schema->nodetype & (LYS_LEAF | LYS_LEAFLIST)",
    file=0x7ffff7f8e000 "/home/irfan/opensource/sysrepo/src/sysrepo.c", line=5581, function=0x7ffff7f8fa50 <__PRETTY_FUNCTION__.19> "sr_change_ly2sr") at ./assert/assert.c:101
#6  0x00007ffff7f24017 in sr_change_ly2sr (node=0x7ffff0001ba0, value_str=0x7ffff00026a0 "<some-xml xmlns=\"urn:test\">\n  <elem>value</elem>\n</some-xml>\n", anchor=0x0,
    sr_val_p=0x7ffff7ae57f0) at /home/irfan/opensource/sysrepo/src/sysrepo.c:5581
#7  0x00007ffff7f2465f in sr_get_change_next (session=0x7ffff00057e0, iter=0x7ffff0002d00, operation=0x7ffff7ae57fc, old_value=0x7ffff7ae57f0, new_value=0x7ffff7ae57e8)
    at /home/irfan/opensource/sysrepo/src/sysrepo.c:5699
#8  0x0000555555555960 in module_change_cb (session=0x7ffff00057e0, sub_id=2, module_name=0x555555641a40 "test", xpath=0x0, event=SR_EV_CHANGE, request_id=5, private_data=0x0)
    at /home/irfan/opensource/sysrepo/examples/application_changes_example.c:214
#9  0x00007ffff7f7241d in sr_shmsub_change_listen_process_module_events (change_subs=0x555555643360, conn=0x555555559790) at /home/irfan/opensource/sysrepo/src/shm_sub.c:3398
#10 0x00007ffff7f21682 in sr_subscription_process_events (subscription=0x555555588450, session=0x0, wake_up_in=0x7ffff7ae5c30) at /home/irfan/opensource/sysrepo/src/sysrepo.c:4595
#11 0x00007ffff7f763d3 in sr_shmsub_listen_thread (arg=0x555555588450) at /home/irfan/opensource/sysrepo/src/shm_sub.c:4817
#12 0x00007ffff7d9c134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#13 0x00007ffff7e1c7dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb)
```

I see a crash with the above backtrace.
This can be reproduced by running from one terminal
`$ make -j clean sr_clean test_clean all && gdb tests/test_apply_changes -ex 'b sr_apply_changes' -ex r`

and then launching
`$ gdb ./examples/application_changes_example -ex 'r test'`
from another terminal

and then continue test_apply_changes with
`disable 1`
`continue`

**Comment by michalvasko** [comment]
Thanks, fixed.
