### ISSUE TITLE
member access within null pointer while getting data

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#3425]
Hello,

the following simple program crashes with the logs below.

```
#include <sysrepo-cpp/Session.hpp>
#include <sysrepo-cpp/Connection.hpp>

int main()
{
    std::optional<sysrepo::Connection> conn{std::in_place};
    auto sess = conn->sessionStart(sysrepo::Datastore::Running);

    sess.setItem("/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='infix-routing:ospfv2'][name='default']", std::nullopt);
    sess.applyChanges();

    sess.getData("/ietf-routing:routing/control-plane-protocols/control-plane-protocol[type='ospfv2'][name='default']", 0, sysrepo::GetOptions::Default);

    return 0;
}
```

```
/home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:8276:41: runtime error: member access within null pointer of type 'const struct lysc_node'
    #0 0x77be215445d5 in eval_name_test_with_predicate /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:8276
    #1 0x77be2152c6de in eval_relative_location_path /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:8446
    #2 0x77be21539347 in eval_absolute_location_path /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:8517
    #3 0x77be21507fbb in eval_path_expr /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:8939
    #4 0x77be214e28ae in eval_expr_select /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:9628
    #5 0x77be214df05f in lyxp_eval /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/xpath.c:9736
    #6 0x77be20d74461 in lyd_eval_xpath4 /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:3363
    #7 0x77be20d737f1 in lyd_find_xpath3 /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:3322
    #8 0x77be20d7364c in lyd_find_xpath /home/tomas/zdrojaky/cesnet/dependencies/libyang/src/tree_data.c:3303
    #9 0x77be2044fecb in sr_lyd_find_xpath_root /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/ly_wrap.c:1022
    #10 0x77be204b428e in sr_modinfo_get_filter /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/modinfo.c:3245
    #11 0x77be2038ce84 in sr_get_data /home/tomas/zdrojaky/cesnet/dependencies/sysrepo/src/sysrepo.c:3097
    #12 0x77be23563507 in sysrepo::Session::getData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, sysrepo::GetOptions, std::chrono::duration<long, std::ratio<1l, 1000l> >) const /home/tomas/zdrojaky/cesnet/dependencies/sysrepo-cpp/src/Session.cpp:198
    #13 0x5a1922a6f88c in main /home/tomas/zdrojaky/cesnet/tmp/t.cpp:12
    #14 0x77be21a39c87  (/usr/lib/libc.so.6+0x25c87) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #15 0x77be21a39d4b in __libc_start_main (/usr/lib/libc.so.6+0x25d4b) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #16 0x5a1922a6f2b4 in _start (/home/tomas/zdrojaky/cesnet/tmp/a.out+0xf2b4) (BuildId: 4d2e3ce02e300db5248a95b5b86fa73f035eff99)
```

I am not sure if I can use `[type='ospfv2']` predicate in the path provided to `Session::getData` (`sr_get_data`) or I should use `[type='infix-routing:ospfv2']` (which works fine). Either way, this should probably result in an error, not a crash.

Versions used:
 * sysrepo: `28832faa7985fb4bdcebbfec4485cbd929853f8c`
 * libyang: `526e3ffd1e93ca5874675b48f4027de6150ce92f`

The yang models used can be found here: https://github.com/kernelkit/infix/tree/main/src/confd/yang

Found while working on https://github.com/CESNET/rousette/issues/12

**Comment by michalvasko** [comment]
Fixed.
