### ISSUE TITLE
sysrepocfg_test: stack-buffer-overflow and stack-buffer-underflow

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#551]
Using merged tips of current devel and master (i.e., a merge of sysrepo/sysrepo@5c3a988 and sysrepo/sysrepo@d1d061b), the ``sysrepocfg_test`` fails on an ASAN build with option ``USE_SR_MEM_MGMT:BOOL=OFF``:

```
1/1 Test #47: sysrepocfg_test ..................***Failed    3.06 sec
[==========] Running 6 test(s).
[ RUN      ] srcfg_test_version
[       OK ] srcfg_test_version
[ RUN      ] srcfg_test_help
[       OK ] srcfg_test_help
[ RUN      ] srcfg_test_export
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
[       OK ] srcfg_test_export
[ RUN      ] srcfg_test_editing
../src/sysrepocfg: Invalid datastore specified (select either "running" or "startup").
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.wDIVu4
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.3dYPsi
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.g2qZYA
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.7stWLR
[ERR] (srcfg_import_datastore:661) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()
=================================================================
==3799==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff64572ee0 at pc 0x0000004a038d bp 0x7fff64571d60 sp 0x7fff64571510
WRITE of size 4097 at 0x7fff64572ee0 thread T0
    #0 0x4a038c in scanf_common(void*, int, bool, char const*, __va_list_tag*) /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_format.inc:343
    #1 0x4a1370 in __isoc99_vscanf /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1187
    #2 0x4a1467 in __isoc99_scanf /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1208
    #3 0x517ef9 in srcfg_prompt /home/jkt/work/prog/sysrepo/build/../src/executables/sysrepocfg.c:944:15
    #4 0x513a6f in srcfg_edit_operation /home/jkt/work/prog/sysrepo/build/../src/executables/sysrepocfg.c:1014:14
    #5 0x5124c9 in main /home/jkt/work/prog/sysrepo/build/../src/executables/sysrepocfg.c:1422:18
    #6 0x7f5b93276733 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.22-r4/work/glibc-2.22/csu/libc-start.c:289
    #7 0x41ab18 in _start (/home/jkt/work/prog/sysrepo/build/src/sysrepocfg+0x41ab18)

Address 0x7fff64572ee0 is located in stack of thread T0 at offset 4128 in frame
    #0 0x51771f in srcfg_prompt /home/jkt/work/prog/sysrepo/build/../src/executables/sysrepocfg.c:935

  This frame has 1 object(s):
    [32, 4128) 'input' <== Memory access at offset 4128 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_format.inc:343 in scanf_common(void*, int, bool, char const*, __va_list_tag*)
Shadow bytes around the buggy address:
  0x10006c8a6580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006c8a6590: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006c8a65a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006c8a65b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006c8a65c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10006c8a65d0: 00 00 00 00 00 00 00 00 00 00 00 00[f3]f3 f3 f3
  0x10006c8a65e0: f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 00 00 00 00
  0x10006c8a65f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006c8a6600: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x10006c8a6610: 00 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006c8a6620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3799==ABORTING
0 != 0x1
../tests/helpers/system_helper.c:124: error: Failure!

REGEX: '(.*Unable to apply the changes.*){3}Your changes have been saved to 'sysrepocfg_test-dump.txt''
FILE: ''
[  FAILED  ] srcfg_test_editing
[ RUN      ] srcfg_test_editing
=================================================================
==3503==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffd494fc300 at pc 0x0000004d097c bp 0x7ffd494fc1f0 sp 0x7ffd494fb9a0
WRITE of size 72 at 0x7ffd494fc300 thread T0
    #0 0x4d097b in __asan_memset /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:430
    #1 0x7f412f368c7c in read_sub_module /home/jkt/work/prog/libyang/build/../src/parser_yin.c:5323:5
    #2 0x7f412f36fc86 in yin_read_module /home/jkt/work/prog/libyang/build/../src/parser_yin.c:5933:9
    #3 0x7f412f43862d in lys_parse_mem_ /home/jkt/work/prog/libyang/build/../src/tree_schema.c:863:15
    #4 0x7f412f4383a4 in lys_parse_mem /home/jkt/work/prog/libyang/build/../src/tree_schema.c:880:12
    #5 0x7f412f2dde0e in ly_ctx_new /home/jkt/work/prog/libyang/build/../src/context.c:102:39
    #6 0x52515c in createDataTreeIETFinterfacesModule /home/jkt/work/prog/sysrepo/build/../tests/helpers/test_module_helper.c:376:26
    #7 0x529ef2 in srcfg_test_set_running_datastore /home/jkt/work/prog/sysrepo/build/../tests/sysrepocfg_test.c:218:5
    #8 0x7f41301e9e45 in cmocka_run_one_test_or_fixture /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2310
    #9 0x7f41301ea4b7 in cmocka_run_one_tests /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2395
    #10 0x7f41301ea4b7 in _cmocka_run_group_tests /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2518
    #11 0x527ac9 in main /home/jkt/work/prog/sysrepo/build/../tests/sysrepocfg_test.c:1088:11
    #12 0x7f412e7ec733 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.22-r4/work/glibc-2.22/csu/libc-start.c:289
    #13 0x42bef8 in _start (/home/jkt/work/prog/sysrepo/build/tests/sysrepocfg_test+0x42bef8)

Address 0x7ffd494fc300 is located in stack of thread T0==3503==AddressSanitizer CHECK failed: /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_thread.cc:314 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0)
    #0 0x4f305b in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_rtl.cc:67
    #1 0x50dd5e in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4f883a in __asan::AsanThread::GetStackFrameAccessByAddr(unsigned long, __asan::AsanThread::StackFrameAccess*) /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_thread.cc:314
    #3 0x4ecc20 in __asan::DescribeAddressIfStack(unsigned long, unsigned long) /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_report.cc:461
    #4 0x4ed302 in __asan::DescribeAddress(unsigned long, unsigned long, char const*) /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_report.cc:588
    #5 0x4eddd0 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) [clone .part.19] /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_report.cc:1194
    #6 0x4d099d in __asan_memset /var/tmp/portage/sys-devel/llvm-3.9.0/work/llvm-3.9.0.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:430
    #7 0x7f412f368c7c in read_sub_module /home/jkt/work/prog/libyang/build/../src/parser_yin.c:5323:5
    #8 0x7f412f36fc86 in yin_read_module /home/jkt/work/prog/libyang/build/../src/parser_yin.c:5933:9
    #9 0x7f412f43862d in lys_parse_mem_ /home/jkt/work/prog/libyang/build/../src/tree_schema.c:863:15
    #10 0x7f412f4383a4 in lys_parse_mem /home/jkt/work/prog/libyang/build/../src/tree_schema.c:880:12
    #11 0x7f412f2dde0e in ly_ctx_new /home/jkt/work/prog/libyang/build/../src/context.c:102:39
    #12 0x52515c in createDataTreeIETFinterfacesModule /home/jkt/work/prog/sysrepo/build/../tests/helpers/test_module_helper.c:376:26
    #13 0x529ef2 in srcfg_test_set_running_datastore /home/jkt/work/prog/sysrepo/build/../tests/sysrepocfg_test.c:218:5
    #14 0x7f41301e9e45 in cmocka_run_one_test_or_fixture /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2310
    #15 0x7f41301ea4b7 in cmocka_run_one_tests /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2395
    #16 0x7f41301ea4b7 in _cmocka_run_group_tests /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2518
    #17 0x527ac9 in main /home/jkt/work/prog/sysrepo/build/../tests/sysrepocfg_test.c:1088:11
    #18 0x7f412e7ec733 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.22-r4/work/glibc-2.22/csu/libc-start.c:289
    #19 0x42bef8 in _start (/home/jkt/work/prog/sysrepo/build/tests/sysrepocfg_test+0x42bef8)



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   3.07 sec

The following tests FAILED:
         47 - sysrepocfg_test (Failed)
Errors while running CTest
```

**Comment by milanlenco** [comment]
stack-buffer-underflow is most likely a false positive (https://github.com/CESNET/libyang/issues/203).
Closing the issue.
