### ISSUE TITLE
sysrepo-libyang crashed when deal union data

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#859]
sysrepo-libyang crashed when deal union data use netopeer
 
**The module is** 
```yang
module UnionRoot {
    namespace "urn:union:params:xml:ns:yang:ran:UnionRoot";
    prefix ME;

    organization  "union team";

    description  "union Element";   

    revision "2016-12-15" {
        description  "Initial Version.";
        reference  "ostack";
    }
	
    typedef "UnionType" {
        type "union" {
            type int32;
            type decimal64 { fraction-digits 1;}
            type boolean;
            type enumeration {enum EnumVal;}
            type bits{bit bitVal;}
			type string;
        }
    }

	grouping moId4List {
        leaf moId{
            type string;
        }
    }
	
	grouping UnionRootGrouping_List {
        list UnionRootGroupingList {
            key "moId";           
            uses moId4List;
            leaf unionLeafInRootGrouping { type UnionType;}
        } 
    }
	
	container UnionRoot {
		leaf userLabel{ type string; }
		list UnionRootList {
            key "moId";           
            uses moId4List;
            leaf unionLeafInListRoot { type UnionType;}
        } 
        uses UnionRootGrouping_List;  		
    }
}
```

**the xml data** 
```xml
<UnionRoot xmlns="urn:union:params:xml:ns:yang:ran:UnionRoot" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<UnionRootList>
		<moId>1</moId>
		<unionLeafInListRoot>TestString</unionLeafInListRoot>
	</UnionRootList>
	<UnionRootList>
		<moId>2</moId>
		<unionLeafInListRoot>100</unionLeafInListRoot>
	</UnionRootList>
	<UnionRootList>
		<moId>3</moId>
		<unionLeafInListRoot>100.1</unionLeafInListRoot>
	</UnionRootList>
	<UnionRootList>
		<moId>4</moId>
		<unionLeafInListRoot>false</unionLeafInListRoot>
	</UnionRootList>
	<UnionRootList>
		<moId>5</moId>
		<unionLeafInListRoot>EnumVal</unionLeafInListRoot>
	</UnionRootList>
	<UnionRootList>
		<moId>6</moId>
		<unionLeafInListRoot>bitVal</unionLeafInListRoot>
	</UnionRootList>
</UnionRoot>
```
**the sysrepo bt log**
```
[DBG] [140737315649280] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=34, count=0.
[DBG] [140737315649280] (rp_set_item_req_process:1162) Processing set_item request.
[INF] [140737315649280] (rp_dt_set_item_wrapper:575) Set item request running datastore, xpath: /UnionRoot:UnionRoot/UnionRootList[moId='6']/unionLeafInListRoot
[DBG] [140737315649280] (dm_get_data_info_internal:2653) Module UnionRoot already loaded
[DBG] [140737315649280] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=5, current count=1.
[DBG] [140737315649280] (rp_worker_thread_execute:3716) Thread id=140737315649280 will wait.
[DBG] [140737354061632] (cm_msg_enqueue_cb:1718) New message enqueued into CM message queue.
[DBG] [140737354061632] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=6, count=0.
[DBG] [140737354061632] (cm_conn_out_buff_flush:505) Sending 27 bytes of data.
[DBG] [140737354061632] (cm_conn_out_buff_flush:511) 27 bytes of data sent.
[DBG] [140737354061632] (cm_conn_read_cb:1106) fd 10 readable
[DBG] [140737354061632] (cm_conn_read_cb:1119) 27 bytes of data received on fd 10
[DBG] [140737354061632] (cm_conn_read_cb:1129) fd 10 would block
[DBG] [140737354061632] (cm_conn_in_buff_process:1059) New message of size 23 bytes received.
[DBG] [140737354061632] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=34, current count=1.
[DBG] [140737354061632] (rp_msg_process:4111) Threads: active=0/4, 1 requests in queue
[DBG] [140737307256576] (rp_worker_thread_execute:3728) Thread id=140737307256576 signaled.
[DBG] [140737307256576] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=35, count=0.
[DBG] [140737307256576] (rp_commit_req_process:1424) Processing commit request.
[DBG] [140737307256576] (rp_dt_commit:813) Commit (1/10): process started

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff534a700 (LWP 458)]
0x00007ffff6ca86ce in lyv_data_content (node=0x7fffe814fa90, options=16897, unres=0x7fffdc052430) at /root/ostack/libyang/src/validation.c:440
440     /root/ostack/libyang/src/validation.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-78.el7.x86_64 pcre-8.32-14.el7.x86_64 protobuf-c-1.0.2-2.el7.x86_64
(gdb) bt
#0  0x00007ffff6ca86ce in lyv_data_content (node=0x7fffe814fa90, options=16897, unres=0x7fffdc052430) at /root/ostack/libyang/src/validation.c:440
#1  0x00007ffff6d17cec in lyd_validate (node=0x7fffec004390, options=16897, var_arg=0x7fffe41a1c30) at /root/ostack/libyang/src/tree_data.c:4205
#2  0x00007ffff7ac2c86 in dm_validate_data_info (dm_ctx=0x634010, session=0x64ef60, info=0x7fffec004380) at /root/ostack/sysrepo/src/data_manager.c:2612
#3  0x00007ffff7ac8659 in dm_validate_session_data_trees (dm_ctx=0x634010, session=0x64ef60, errors=0x7ffff5349da0, err_cnt=0x7ffff5349d98)
    at /root/ostack/sysrepo/src/data_manager.c:3123
#4  0x00007ffff7aa5e51 in rp_dt_commit (rp_ctx=0x6048f0, session=0x6891d0, c_ctx=0x0, errors=0x7ffff5349da0, err_cnt=0x7ffff5349d98)
    at /root/ostack/sysrepo/src/rp_dt_edit.c:817
#5  0x00007ffff7a63a5e in rp_commit_req_process (rp_ctx=0x6048f0, session=0x6891d0, msg=0x68af98, skip_msg_cleanup=0x7ffff5349e9b)
    at /root/ostack/sysrepo/src/request_processor.c:1459
#6  0x00007ffff7a79abc in rp_req_dispatch (rp_ctx=0x6048f0, session=0x6891d0, msg=0x68af98, skip_msg_cleanup=0x7ffff5349e9b)
    at /root/ostack/sysrepo/src/request_processor.c:3388
#7  0x00007ffff7a7b0db in rp_msg_dispatch (rp_ctx=0x6048f0, session=0x6891d0, msg=0x68af98) at /root/ostack/sysrepo/src/request_processor.c:3574
#8  0x00007ffff7a7bb4a in rp_worker_thread_execute (rp_ctx_p=0x6048f0) at /root/ostack/sysrepo/src/request_processor.c:3675
#9  0x00007ffff75aadf5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff69b31ad in clone () from /lib64/libc.so.6
```

**Comment by michalvasko** [comment]
Hi,
it should be fixed, but for it to work properly, you will need to update *libyang* (the referenced commit), *netopeer2-server* ([netopeer2 commit](https://github.com/CESNET/Netopeer2/commit/cc322c06e62e7623f4a7d4d11fbdea7c2cd4fd97)) and *sysrepo* (#863).

Regards,
Michal
