### ISSUE TITLE
Memory leak in sysrepocfg_test, srcfg_test_editing

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#991]
```
2017-11-16 17:04:48,313 [output] 26/28 Test #26: sysrepocfg_test ..................***Failed    9.28 sec
2017-11-16 17:04:48,313 [output] [==========] Running 8 test(s).
2017-11-16 17:04:48,313 [output] [ RUN      ] srcfg_test_version
2017-11-16 17:04:48,313 [output] [       OK ] srcfg_test_version
2017-11-16 17:04:48,313 [output] [ RUN      ] srcfg_test_help
2017-11-16 17:04:48,313 [output] [       OK ] srcfg_test_help
2017-11-16 17:04:48,314 [output] [ RUN      ] srcfg_test_export
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Unsupported data format (xml and json are supported).
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Module name is not specified.
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Unsupported data format (xml and json are supported).
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Module name is not specified.
2017-11-16 17:04:48,314 [output] [       OK ] srcfg_test_export
2017-11-16 17:04:48,314 [output] [ RUN      ] srcfg_test_editing
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Invalid datastore specified (select either "running" or "startup").
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Unsupported data format (xml and json are supported).
2017-11-16 17:04:48,314 [output] ../src/sysrepocfg: Module name is not specified.
2017-11-16 17:04:48,315 [output] ../src/sysrepocfg: Unsupported data format (xml and json are supported).
2017-11-16 17:04:48,315 [output] ../src/sysrepocfg: Module name is not specified.
2017-11-16 17:04:48,315 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,315 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.UdNguN
2017-11-16 17:04:48,315 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,315 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.yzshOI
2017-11-16 17:04:48,315 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,315 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.FsxSAu
2017-11-16 17:04:48,316 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,316 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.Mizssf
2017-11-16 17:04:48,316 [output] [ERR] (srcfg_import_datastore:801) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()
2017-11-16 17:04:48,316 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,316 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.Mizssf
2017-11-16 17:04:48,316 [output] [ERR] (srcfg_import_datastore:801) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()
2017-11-16 17:04:48,316 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,316 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.Mizssf
2017-11-16 17:04:48,316 [output] [ERR] (srcfg_import_datastore:801) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()
2017-11-16 17:04:48,317 [output] + '[' 1 -ne 1 ']'
2017-11-16 17:04:48,317 [output] + cp sysrepocfg_test-new_config.txt /tmp/srcfg.example-module.startup.rpvvUC
2017-11-16 17:04:48,317 [output] =================================================================
2017-11-16 17:04:48,317 [output] ==30446==ERROR: LeakSanitizer: detected memory leaks
2017-11-16 17:04:48,317 [output] Direct leak of 14 byte(s) in 2 object(s) allocated from:
2017-11-16 17:04:48,317 [output]     #0 0x7f8a9fd3b180 in strdup (/lib64/libasan.so.3+0x5a180)
2017-11-16 17:04:48,317 [output]     #1 0x7f8a9f730b81 in sr_mem_edit_string /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/src/common/sr_mem_mgmt.c:443
2017-11-16 17:04:48,317 [output]     #2 0x7f8a9f6d8118 in sr_libyang_leaf_copy_value /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/src/common/sr_utils.c:1196
2017-11-16 17:04:48,317 [output]     #3 0x409ae8 in srcfg_convert_lydiff_created /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/src/executables/sysrepocfg.c:622
2017-11-16 17:04:48,317 [output]     #4 0x40ce54 in srcfg_import_datastore /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/src/executables/sysrepocfg.c:887
2017-11-16 17:04:48,318 [output]     #5 0x41334d in srcfg_edit_operation /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/src/executables/sysrepocfg.c:1553
2017-11-16 17:04:48,318 [output]     #6 0x4151d7 in main /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/src/executables/sysrepocfg.c:1994
2017-11-16 17:04:48,318 [output]     #7 0x7f8a9e322b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
2017-11-16 17:04:48,318 [output] SUMMARY: AddressSanitizer: 14 byte(s) leaked in 2 allocation(s).
2017-11-16 17:04:48,318 [output] [bt] #0 /home/turbo-hipster/jobs/bcf39866411a/51/551/2/check/check-czechlight-devtoolset6-sanitizers-el7/29531d6/build-sysrepo-tests/tests/sysrepocfg_test(assert_int_equal_bt+0x20) [0x41e10d]
2017-11-16 17:04:48,318 [output]         /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/helpers/system_helper.c:266
2017-11-16 17:04:48,318 [output] [bt] #1 /home/turbo-hipster/jobs/bcf39866411a/51/551/2/check/check-czechlight-devtoolset6-sanitizers-el7/29531d6/build-sysrepo-tests/tests/sysrepocfg_test(exec_shell_command+0x218) [0x41ed58]
2017-11-16 17:04:48,318 [output]         /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/helpers/system_helper.c:446
2017-11-16 17:04:48,318 [output] [bt] #2 /home/turbo-hipster/jobs/bcf39866411a/51/551/2/check/check-czechlight-devtoolset6-sanitizers-el7/29531d6/build-sysrepo-tests/tests/sysrepocfg_test() [0x424758]
2017-11-16 17:04:48,319 [output]         /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/sysrepocfg_test.c:918
2017-11-16 17:04:48,319 [output] c:446
2017-11-16 17:04:48,319 [output] [bt] #3 /lib64/libcmocka.so.0(+0x45fd) [0x7f83d6f755fd]
2017-11-16 17:04:48,319 [output]         ??:0
2017-11-16 17:04:48,319 [output] /turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/sysrepocfg_test.c:918
2017-11-16 17:04:48,319 [output] c:446
2017-11-16 17:04:48,319 [output] [bt] #4 /lib64/libcmocka.so.0(_cmocka_run_group_tests+0x2f7) [0x7f83d6f75d47]
2017-11-16 17:04:48,319 [output]         ??:0
2017-11-16 17:04:48,319 [output] /turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/sysrepocfg_test.c:918
2017-11-16 17:04:48,319 [output] c:446
2017-11-16 17:04:48,320 [output] [bt] #5 /home/turbo-hipster/jobs/bcf39866411a/51/551/2/check/check-czechlight-devtoolset6-sanitizers-el7/29531d6/build-sysrepo-tests/tests/sysrepocfg_test(main+0x72b) [0x4258fc]
2017-11-16 17:04:48,320 [output]         /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/sysrepocfg_test.c:1298
2017-11-16 17:04:48,320 [output] :446
2017-11-16 17:04:48,320 [output] [bt] #6 /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f83d5ca2b35]
2017-11-16 17:04:48,320 [output]         ??:0
2017-11-16 17:04:48,320 [output] /turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/sysrepocfg_test.c:1298
2017-11-16 17:04:48,320 [output] :446
2017-11-16 17:04:48,320 [output] [bt] #7 /home/turbo-hipster/jobs/bcf39866411a/51/551/2/check/check-czechlight-devtoolset6-sanitizers-el7/29531d6/build-sysrepo-tests/tests/sysrepocfg_test() [0x419009]
2017-11-16 17:04:48,320 [output]         ??:?
2017-11-16 17:04:48,320 [output] /turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/sysrepocfg_test.c:1298
2017-11-16 17:04:48,321 [output] :446
2017-11-16 17:04:48,321 [output] 0 != 0x1
2017-11-16 17:04:48,321 [output] /home/turbo-hipster/git/bcf39866411a/CzechLight/cla-sysrepo/submodules/sysrepo/tests/helpers/system_helper.c:266: error: Failure!
2017-11-16 17:04:48,321 [output] [  FAILED  ] srcfg_test_editing
```

**Comment by michalvasko** [comment]
Hi,
it seems to me you encountered this leak because the test failed (no proper cleanup in that case), am I wrong?

Regards,
Michal
